### ISSUE TITLE
SPXZ mobile wallet for sapling

### ISSUE THREAD

**Issue by omershlo** [ZcashFoundation/GrantProposals-2018Q2#10]

**Comment by b-g-goodell** [comment]
Can you elaborate on some of the practical differences between your proposal and a simple 2FA set-up?

**Comment by omershlo** [comment]
2FA and our proposal are not fully comparable

**Comment by tromer** [comment]
Regarding the "X" (delegated proving): the upcoming Sapling upgrade will drastically reduce resource consumption shielded transaction generation (and in particular, the zkSNARK proving). See https://blog.z.cash/cultivating-sapling-faster-zksnarks (as well as the [protocol spec](https://github.com/zcash/zips/blob/master/protocol/protocol.pdf) and other upcoming blog posts), and related discussion in #32. How does this affect your proposal? Will there still be a need for such proving-as-a-service?

How will authentication with the server work? In particular, if the credentials for using the server's share of the key are cached on the mobile device (for usability), then an attacker in control of the mobile device can spend the funds.

**Comment by tromer** [comment]
Can you also say more about your implementation (e.g., the client and server software stacks) and milestones?

**Comment by omershlo** [comment]
@tromer: 
Regarding the 'X' : our intention is to provide shielded transaction to mobile clients using Sapling.

**Comment by omershlo** [comment]
Please let us know if further information is required.

**Comment by tromer** [comment]
The Zcash Foundation Grant Review committee has reviewed your pre-proposal, including the above discussion, to evaluate its potential and competitiveness relative to other proposals. Every pre-proposal was evaluated by at least 4 committee members .

The committee's opinion is that *your pre-proposal is not a leading candidate for funding in this round*, and the committee therefore does not invite you to submit a full proposal.
This decision is advisory, and you can still choose to submit a full proposal by June 15th, following the detailed structure described in the [Call for Proposals](https://github.com/ZcashFoundation/GrantProposals-2018Q2). Note that if the full proposal is substantially the same as discussion so far reflects, then it's unlikely to be chosen for funding; and if it isn't, then we encourage you to post a draft (or at least answer any open questions) as early as possible, to allow for community feedback. Regardless of your choice, we thank you for participation thus far.
