### ISSUE TITLE
localz.cash

### ISSUE THREAD

**Issue by bijarkhan** [ZcashFoundation/GrantProposals-2018Q2#11]
In addition to the functionality already available for other coins on websites such as 'localbitcoins.com', 'localz.cash' (Local Zcash) will seek to provide concise information for users in need of private financial services. The development process would begin by mirroring the functionality of 'localbitcoins.com', with a more simplistic frontend design; this will allow us to ensure development costs are spent on the functionality and transparency before we turn our attention to platform growth and user experience changes.

I would use any financial assistance received to hire the necessary freelancers to develop the initial build of the website, utilizing as many freely available tools as possible. The goal is to have the entire codebase to be publicly available so that users an ensure that as long as they follow the directions on our website, their communications will be secure.

Eventually, I would like the website's design to be able to walk a user down simple tracks, such as:

- "I want to send a Zcash payment anonymously"
- "I want to receive a Zcash payment anonymously"

This could provide opportunities for advertising to users in a way that actually benefits them, by partnering with VPN providers that respect user privacy, as well as offering free advertising to other community tools and projects that would be of benefit to our users. The goal is for the website to operate like a nonprofit, and to bolster the Zcash community; if needs or complexity grow to a point where it should be classified as a nonprofit, that will certainly be explored.

I will concede that I have never built a website, or web app, but I have been in touch with independent web-developers to ballpark the project. It could cost between $12,000 - $15,000 for the most simplistic interpretation, but I intend to create the user guides and materials for free myself. I look forward to hearing any questions, comments, or concerns about this project; thanks for reading! :)

-b

**Comment by bijarkhan** [comment]
Ideally, the website should be welcoming and simple enough for a user with no cryptocurrency experience to be able to create an account, arrange a Zcash sale or purchase, and conduct the transaction completely privately while being walked through each step. 

Similarly to checklists for buying a car or motorcycle privately, covering thingss like "Did you check for rust?", and "Are there signs the vehicle was used for racing?", our user on-boarding process would ask users questions like "Is your IP currently protected with a VPN?", and "Are you sure your device is secure?" that would provide engaging scenarios and reasons for users to care about their privacy, in addition to the resources covering how to actually do that.

**Comment by tromer** [comment]
The Zcash Foundation Grant Review committee has reviewed your pre-proposal, including the above discussion, to evaluate its potential and competitiveness relative to other proposals. Every pre-proposal was evaluated by at least 4 committee members .

The committee's opinion is that *your pre-proposal is not a leading candidate for funding in this round*, and the committee therefore does not invite you to submit a full proposal.
This decision is advisory, and you can still choose to submit a full proposal by June 15th, following the detailed structure described in the [Call for Proposals](https://github.com/ZcashFoundation/GrantProposals-2018Q2). Note that if the full proposal is substantially the same as discussion so far reflects, then it's unlikely to be chosen for funding; and if it isn't, then we encourage you to post a draft (or at least answer any open questions) as early as possible, to allow for community feedback. Regardless of your choice, we thank you for participation thus far.
