### ISSUE TITLE
Research for best practice on PoW implementation and support

### ISSUE THREAD

**Issue by hosseamin** [ZcashFoundation/GrantProposals-2018Q2#12]
I'm not submitting this proposal for my self. There should be others more qualified that me. I think zcash needs it.

Equihash was first used for zcash for best distribution practice for generated coins. Which did its job for some period of time.

We are currently are discussing what is the appropriate action that can be done after bitmain released their Equihash miners.
Here's my thought on this.

Another issue with Equihash is that capital cost for producing ASIC for it is very high. Probably that’s why it came last. Meaning the game will be for giants to play their big moves, startups for manufacturing such a thing is dead, unless with VC fund.
All I’m trying to say keeping Equihash as is, is a mistake.

Equihash is no longer is fulfilling its goal. It's time for change.

There is a discussion on issue with banning ASIC miners for certain people or jurisdictions. Which i too think is a problem.

One of these two researches maybe worth doing.

# Proof-Of-Work change periodically

This change is great for GPU miners. And the issue about banning ASICs. Since we are already planning to do hard forks. There's no such restriction bitcoin has.

A research for performing this change and keeping the security of the network.

# Next Proof-Of-Work as a project

There was discussion for designing an ASIC and open-sourcing it for an effort to solve the issue with monopoly that we have with ASIC miners.
Doing this for Equihash is just a dead project. Since bitmain already did it, And it's unlikely for them to open-source their miners.

The research should come up with a plan to change PoW, open-sourced ASIC board and chip design with working beta version. The project can benefit financially for being a distributor of ASIC chips. This project allows for better competition at this area.

Shipping cost of an ASIC miner from china is about 150USD. It will take about 2 weeks to get were you want it. 
There's incentive to have multiple manufacturers in different places. Another good thing that it can do is to create jobs were the miner lives. Instead of giving all the profits to a single entity.

There's no simple solution for having a healthy PoW. I should also point that the reason for us being here is the importance of PoW.

**Comment by b-g-goodell** [comment]
If this proposal is approved, who gets the money and does the work?

**Comment by tromer** [comment]
The Zcash Foundation Grant Review committee has reviewed your pre-proposal, including the above discussion, to evaluate its potential and competitiveness relative to other proposals. Every pre-proposal was evaluated by at least 4 committee members .

The committee's opinion is that *your pre-proposal is not a leading candidate for funding in this round*, and the committee therefore does not invite you to submit a full proposal.
This decision is advisory, and you can still choose to submit a full proposal by June 15th, following the detailed structure described in the [Call for Proposals](https://github.com/ZcashFoundation/GrantProposals-2018Q2). Note that if the full proposal is substantially the same as discussion so far reflects, then it's unlikely to be chosen for funding; and if it isn't, then we encourage you to post a draft (or at least answer any open questions) as early as possible, to allow for community feedback. Regardless of your choice, we thank you for participation thus far.
