### ISSUE TITLE
Demystify Cryptocurrencies and Privacy Coins Among Arabs/Refugees

### ISSUE THREAD

**Issue by moeghashim** [ZcashFoundation/GrantProposals-2018Q2#13]
It's true that the interest in cryptocurrencies is growing around the world and it's no different in the Arab world. However the scale is small despite the benefits that cryptocurrencies could offer.

There are a few reasons why cryptocurrencies' interest hasn't pickup yet among Arabs and refugees. And they are:

- Governments and banks are fighting cryptocurrency trading.

- There is little content about cryptocurrencies and how to store, transact, buy/sell.

- The lack of understanding the benefit of being able to pay and get paid in cryptocurrency.

- Realize the privacy feature in privacy coins and the fact that they (holders) can't be traced, nor the transactions. And this is a major feature to Arabs. 

My proposal is to work on building educational materials curated for Arabs and refugees to help them understand the potential of cryptocurrencies and focus on the their use cases and how it can help them overcome obstacles they face on daily basis.

**Comment by b-g-goodell** [comment]
Is there a reason to restrict this to the Arab part of the world rather than a general educational grant for various rural communities across the world?

What sort of materials would this project produce? Can you provide some examples of the sorts of materials you want to produce, and explain how these materials would find their way into the intended communities?

**Comment by moeghashim** [comment]
Answering the first question: There reason of making this restrictive to the Arab part of the world is to address a specific pain. And I think it will make a bigger impact rather a general purpose educational grant. The pain is split between two cases:
1- In the Arab world there are 6 counties who suffered and still suffering from war: Syria, Yemen, Libya and Iraq. There are refugees in neighboring counties and refugees within the same countries. The current situation represent a major challenge for refugees to send and receive money abroad. Which means the refugees face challenges receiving money from their relatives and when they manage to receive money from abroad, they end up paying 10-15% between the difference in exchange rate, fees to multiple parties until the money arrives to their hand.
2- The Arab world in general in unstable because of war, conflicts and dictatorship. People in the Arab world could resort to cryptocurrencies as a mobile and secure store of value.

Answering the second question: 
The materials: Video content and blog posts. But I'm planning to support the content with a Twitter account that engages with Arabs regarding cryptocurrencies use cases, share the produced material and engage in conversations. In addition to workshops to showcase real case scenarios. 
There are many ways to engages with the intended communities, working with organisations supporting refugees could be a good start. Tech hubs as well.

An example of the material is: an infographic comparing a transfer of 100 Euro from a refugee in Germany to their relatives in Syria and compare: speed and fees.

**Comment by zookozcash** [comment]
Related: BitOasis recently started offering Zcash in United Arab Emirates, Saudi Arabia, Kuwait, Bahrain, and Oman: https://bitoasisblog.net/2018/04/23/launching-zcash-on-bitoasis-trading-exchange/

BitOasis's exchange support and this proposal would presumably complement each other.

**Comment by moeghashim** [comment]
Yeah, and I know the founder of BitOasis. I'm planning to approach her to see how we can work on something together.

**Comment by tromer** [comment]
The Zcash Foundation Grant Review committee has reviewed your pre-proposal, including the above discussion, to evaluate its potential and competitiveness relative to other proposals. Every pre-proposal was evaluated by at least 4 committee members .

The committee's opinion is that *your pre-proposal is not a leading candidate for funding in this round*, and the committee therefore does not invite you to submit a full proposal.
This decision is advisory, and you can still choose to submit a full proposal by June 15th, following the detailed structure described in the [Call for Proposals](https://github.com/ZcashFoundation/GrantProposals-2018Q2). Note that if the full proposal is substantially the same as discussion so far reflects, then it's unlikely to be chosen for funding; and if it isn't, then we encourage you to post a draft (or at least answer any open questions) as early as possible, to allow for community feedback. Regardless of your choice, we thank you for participation thus far.
