### ISSUE TITLE
Contribute to Monero's Forum Funding System (FFS)

### ISSUE THREAD

**Issue by amiller** [ZcashFoundation/GrantProposals-2018Q2#17]
_Proposal:_ $10k contribution to Monero's Forum Funding System (FFS)

_Motivation:_ Monero is privacy-centric cryptocurrency, and thus a peer of Zcash. Cooperation with other privacy-preserving cryptocurrencies is part of our [VALUES](https://github.com/ZcashFoundation/ZcashFoundation/blob/master/VALUES.md), and furthers the foundation's [MISSION](https://github.com/ZcashFoundation/ZcashFoundation/blob/master/MISSION.md) of providing decentralized privacy-preserving infrastructure for everyone. Monero's FFS  has been a success so far, providing funding for several research projects, development, and community support. It's been an inspiration for our own grant proposal system. 

[(FFS Main Thread)](https://forum.getmonero.org/7/open-tasks/2379/forum-funding-system-ffs-sticky) [(FFS Completed Tasks)](https://forum.getmonero.org/22/completed-tasks) [(FFS Open Tasks)](https://forum.getmonero.org/7/open-tasks) 

_Details:_ I've reached out to one of the moderators of FFS, @rehrar, for ideas of how this could go.

- Option 1: Contribute to the general fund, and let Monero FFS sort out what to fund.

This is the lowest effort way to do it. Nothing wrong with that, but probably a missed opportunity to interact more closely.

- Option 2: Pick a few projects that are particularly well suited to matched funding from Zcash and Monero

    - The current open hardware wallet Kastelo. You can see the open proposal here: https://forum.getmonero.org/8/funding-required/90126/advancing-monero-hardware-wallet. It might be possible to implement Zcash Sapling on this as well.
    - Security auditing for Bulletproofs. Investing in alternative ZKP systems (and especially no-setup) is a priority for us
    - .... more? We can discuss more during the feedback suggestion for this proposal

_Evaluation and follow up:_ After 6 months I'll write a report on how the projects have gone and what impact they've had for the Zcash community.

**Comment by sonyamann** [comment]
I think this is an excellent idea. It would also benefit further iterations of our grants program by broadening people's conceptions of what proposals are eligible. Perhaps we should consider something similar with ZenCash as well.

**Comment by rehrar** [comment]
Heyo, rehrar here. Glad that this is materializing. I can't speak for the whole Monero community (nobody can), but I for one am really excited at this opportunity, and pushing forward together for privacy technology.

If there's anything I can do to help this process along, please do let me know. There will potentially be a few more proposals popping up into the Funding Required section of the coming days/week, and I'll let you guys know if there's anything else that this proposal might be interested in.

**Comment by rehrar** [comment]
The bulletproofs FFS is live: https://forum.getmonero.org/8/funding-required/90007/bulletproofs-audit-fundraising

**Comment by b-g-goodell** [comment]
I'll be recusing myself from this one :)

**Comment by rex4539** [comment]
I'm definitely not in favor of giving a carte blanche to the Monero FFS.

I would prefer that the Monero folks submit a formal proposal for a specific project so we can evaluate if it is worth funding or not.

**Comment by amiller** [comment]
@rex4539 have you looked through the open and past FFS proposals? I think we can evaluate if they're worth funding without them having to make them come here. Explicitly observing how other similar funding efforts work is part of the value of this.

Looking at the open tasks as of today (I only see four):
- The [Bullet Proofs Auditing](https://forum.getmonero.org/8/funding-required/90007/bulletproofs-audit-fundraising) proposal in FFS is related to #31 here (same proposer, different activity).

- I suppose the [hardware wallet one](https://forum.getmonero.org/8/funding-required/90126/advancing-monero-hardware-wallet) would be most compelling if the proposer posted here and gave an indication whether support for Zcash would be included. I will reach out to them during the informal feedback phase.

- The tracking challenge seems to be voted down and may be subsumed by similar privacy analysis proposals to our own system e.g. #27  #39 
https://forum.getmonero.org/8/funding-required/88145/monero-tracking-challenge-2

- Bug bounty for Monero is reasonable but generic. However, this reminds me that we should also consider hosting a formal bug bounty for Zcash, I think Zcash does not have a HackerOne or coordinated disclosure policy, here's an open issue https://github.com/zcash/zcash/issues/1253

What we could do, and I'll write an update about this during the discussion phase, is reserve some amount for FFS proposals and define now some policy how we'll decide to spend it. Options include: I could decide unilaterally among FFS tickets, form a committee to evaluate them, or use a Helios vote or some other experiment (lets see how the June one goes). 

Personally I think even a carte blanche contribution to FFS is not bad, based on their prior completed tasks. https://forum.getmonero.org/22/completed-tasks

**Comment by tromer** [comment]
Is it sufficiently clear that the Monero FFS is sufficiently well aligned with the Foundation's mission that a carte blanche would be appropriate?

I would prefer to see this proposal broken down into a separate issues for the specific projects, so that they can be discussed and prioritized separately.

**Comment by tromer** [comment]
The grant review committee needs further information, as discussed above, in order to evaluate your proposal.

**Comment by amiller** [comment]
I'll first address the broad form of this question:
> Is it sufficiently clear that the Monero FFS is sufficiently well aligned with the Foundation's mission that a carte blanche would be appropriate?

I would answer this in the affirmative, based on past activities. Looking at the log of [(FFS Completed Tasks)](https://forum.getmonero.org/22/completed-tasks),
there's a list of about 20 projects in total since 2015. I could roughly categorize these into three categories:
1. (12x) funding for development (core development, wallet integration, documentation, Kovri)
2. (5x) community outreach (meetups, travel for talks, explainer videos)
3. (4x) research (mostly funding for Monero Research Lab contributors)

Each of the posts comes along with a task list, open comments (which are fairly active, mostly around 10-50 replies), and milestones/updates from the proposer. Looking at the list of currently-in-progress projects (about 50 more of them) the distribution appears roughly the same. And all of these are on topic for improving Monero, and seem to be a fairly similar spread of project topics we have funded for Zcash.

Probably the trickier question is, to what degree does improving Monero achieve the mission of Zcash Foundation. I think it does, even though I also think we should focus primarily on Zcash. My opinion is that the diplomatic gesture of a small carte blanche contribution and precedent for collaboration it sets outweighs the expense of scope.

Let me know if this explanation is helpful. As for providing a breakdown of specific projects to fund....  among the list of current open tasks, actually I'm not excited about any of them enough to give a detailed proposal. That could simply be a selection bias, since all the best ones are already in the "currently-in-progress" pile rather than the "yet to be funded" pile :) So judging by past and current performance is the way to go. 

Of the ongoing projects, I'm probably most excited about the Kovri-related projects, since my opinion is p2p network analysis is a weak spot for all privacy oriented cryptocurrencies, including Zcash and Monero, so work on this can directly improve realized privacy to end users, e.g. https://forum.getmonero.org/9/work-in-progress/86967/anonimal-s-kovri-full-time-development-funding-thread
So if this appeals to the committee more than carte blanche, I could rewrite this to be about supporting Kovri development projects in FFS.

(side note: Actually @rehrar I noticed that [this earlier Kovri proposal](https://forum.getmonero.org/9/work-in-progress/87082/proposal-for-kovri-dev) is already completed but never got moved from the in-progress folder to the completed-tasks folder, so my split above between prior/current may be a bit off.)

**Comment by tromer** [comment]
The Zcash Foundation Grant Review committee has reviewed your pre-proposal, including the above discussion, to evaluate its potential and competitiveness relative to other proposals. Every pre-proposal was evaluated by at least 4 committee members .

The committee's opinion is that *your pre-proposal is not a leading candidate for funding in this round*, and the committee therefore does not invite you to submit a full proposal.
This decision is advisory, and you can still choose to submit a full proposal by June 15th, following the detailed structure described in the [Call for Proposals](https://github.com/ZcashFoundation/GrantProposals-2018Q2). Note that if the full proposal is substantially the same as discussion so far reflects, then it's unlikely to be chosen for funding; and if it isn't, then we encourage you to post a draft (or at least answer any open questions) as early as possible, to allow for community feedback. Regardless of your choice, we thank you for participation thus far.

**Comment by amiller** [comment]
pfffffff
ok I'll try to come up with something better

**Comment by tromer** [comment]
Summarizing the above discussion, as well as the Grant Review Committee's deliberations:

The consensus is enthusiastically in favor of awarding Zcash Foundation grants to Monero-led projects that are pertinent to our mission to enable financial privacy. But at the moment there aren't concrete and suitable projects offered for consideration.

We encourage submission of such proposals in future grant funding grounds.
