### ISSUE TITLE
Equihash and Hardware Ecosystem

### ISSUE THREAD

**Issue by earlmai** [ZcashFoundation/GrantProposals-2018Q2#18]
**Motivation and overview**
Secure, Decentralized and Scalable. We would like to propose a hardware solution for the community, by the community.  In addition to providing the PoW Equihash, we would also develop and scope a variety of hardware based solutions for the community to advise upon.  At ePIC, we design, we don’t mine.

ePIC sees the opportunity to be a part of protocol communities and bring our hardware expertise to an active element of protocol development. ePIC is a Trustware developer, we believe the launch of a blockchain protocol represents the merger of software and hardware into Trustware. The lack of collaboration and alignment between software and hardware development drives contentious forking debates fragmenting communities and infrastructure.  Trustware development is the path to long-term secure, decentralized, and scalable blockchains.

**Technical approach**
We are currently in validation of our Equihash hardware design and would like to work on creating an ecosystem for hardware development and decentralization.

The goal is to deliver an open source implementation to the community for further analysis and inspection. From there we will propose various methods and solutions so that the ZeCash community can be in control of not only their software protocol but hardware ecosystem as well.  

ASICs will be apart of the long term vision which drives up performance while being the most power efficient.  With the community in control of the vision, a secure decentralized network can be maintained without fear of bad actors while allowing scalability. 

**Team background and qualifications**
ePIC blockchain is a digital design house focused on providing the processing power for the blockchain.  We have decades of experience in ASIC development and digital design and our team has already completed several designs and is in the late stages of releasing our first ASIC.

Engineering time lead core elements of critical components of AMD’s flagship products, inclusive of the ASICs in multiple generations of Xbox and Playstation. 

**Evaluation plan**
Start off with providing a base Equihash digital design suitable for an FPGA and/or ASIC.  Use the community to evolve the design for maximal performance and efficiency.  Evaluate methods and solutions ensuring decentralization of hardware distribution, sales and mining power.  With hardware in mind, we can find methods to ensure equal access to equipment and protection from one sole actor of monopolizing the processing power. Building an economic model in partnership with a protocol to distribute and decentralize processing power will represent an innovation in the blockchain economy and represent true commercialization of Trustware.  

**Security considerations**
We have always believed that blockchain should have a software and hardware story and the two must work in tandem to create an ecosystem.  Currently today, many are just focused on the software development but we believe that having a hardware roadmap is integral in providing the best blockchain solution out there. Through a Trustware collaboration hardware provenance can be better assured and specification to privacy or transparency made.  

**Schedule**
4 months to release the Equihash design and at the end of 6 months, have several solutions on how to keep hardware decentralized so the community can decide how to proceed.

**Budget and justification**
All money will be used towards engineering efforts and the resources needed to provide a digital design. 3 dedicated resources will be focused on the project full time for 6 months with the average salary around 120k USD per engineer.  A small portion will be for equipment and software licenses for hardware development and FPGA/Linux towers.

**Email address(es) for direct contact**
www.epicblockchain.io
emai@epicblockchain.io

**Comment by bitcartel** [comment]
Is this the same project as the one you just partnered on with AION.network?

> The ePIC-Aion partnership will result in the first open source implementation of Equihash on an FPGA (Field-programmable gate array), producing a 10x efficiency gain over a Graphics Processing Unit (GPU), resulting in a more secure, decentralized, and scalable processing network. 
https://www.epicblockchain.io/blog/2018/5/7/aion-partners-with-epic-blockchain-to-accelerate-equihash-processing

How much funding is AION putting into the project?

Are you seeking funding from any other Equihash based projects, such as Zencash, Bitcoin Gold, Bitcoin Private, etc?

Will the designs and any other intellectual property that comes out of this project be patent free?

Thanks.

**Comment by earlmai** [comment]
The grant we have with the Aion Foundation is to build a hardware ecosystem in their community as they slowly evolve away from PoW.  The design between Equihash (210,9) & (200,9) may seem similar but ePIC's design is heavily modified for FPGAs & Equihash (210,9).  The Aion project is planned to be open source which is aligned with the Aion Foundation.

We've made a last minute decision to attend Consensus in engaging the other protocols that you have mentioned but need help since not everyone is receptive to tweets & emails (Tickets are sold out?) We would like to open a conversation of introducing hardware into the blockchain ecosystem along with any role ePIC can play.

That being said, the purpose of the ZCash Grant would encompass an Equihash (200,9) design and for research into how we can incorporate ASICs into the ecosystem while maintaining decentralization without compromise of privacy.  Our team has brainstormed a few ideas this past week which will require further research and analysis with the end goal to present the solutions to the community.  We strongly believe ASICs offer performance and efficiency over GPUs but also understand the risk of centralization.  The ZCash foundation ultimately has control over our research and if the community comes to agreement on one of our findings, we hope ePIC would be apart of creating this ASIC for the foundation.

At ePIC we are striving to work with the protocol developers and community to address the processing needs of blockchains.  When ePIC was founded, we unanimously agreed that "We Design, We don't Mine"

**Comment by bitcartel** [comment]
> how we can incorporate ASICs into the ecosystem while maintaining decentralization without compromise of privacy.

Very much a Gordian knot...

There were open-source sha256d ASIC designs created for Bitcoin but they failed to prevent centralization (https://github.com/sfards/ASIC-SF3301, https://github.com/GeorgeHahn/Avalon).

> We strongly believe ASICs offer performance and efficiency over GPUs but also understand the risk of centralization.

As you're probably already aware, centralization is a major topic of discussion for the community right now.

- Statement on ASICs: https://z.cash.foundation/blog/statement-on-asics/
- Foundation ballot on ASIC resistance: https://github.com/ZcashFoundation/Elections/pull/1 and https://github.com/amiller/Elections/commit/d0820571a359f682e519d89375dc162570361cd2
- Community discussion: https://forum.z.cash/t/let-s-talk-about-asic-mining/27353/2?filter=summary

Pinging @amiller @tromer as I think this interesting proposal (as currently worded) could prejudice the foundation ballot.

Perhaps ePIC could play defense for ASIC resistant cryptocurrencies? ;-)

**Comment by mineZcash** [comment]
I'm unclear as to what exactly the funding will be used for. Changing the current Equihash 200,9 parameters to 210,9 is trivial from a software perspective. What will 3 engineers be working 6 months full time be working towards? 

You mention FPGA equipment as well as ASIC, what is the end result to be? An ASIC to compete with Bitmain, or an FPGA?

What if Zcash were to simply adopt the same parameters as Aion? Thus reducing the development effort required as well as potentially giving ePIC a large userbase of Zcash miners looking for hardware? 

Can you elaborate on this statement "decentralization of hardware distribution" How exactly do you to intend to honor this?

**Comment by autotunafish** [comment]
I could pick this apart, but its Friday, keep it short, Red flags
Edit- ill be back tomorrow

**Comment by earlmai** [comment]
@bitcartel 
The opensource bitcoin designs you mentioned (I looked quickly) are board/software designs which are missing one key component, the ASIC itself. Considering the performance and efficiency advantage, one should also consider the economies of scale where ASICs are R&D expensive but very cost effective in volume.

GPUs are an ASIC which I've spent over a decade of my career building at my former company. They were honestly meant to do something else with a lot of wasted resources and they don't stop centralization if you look around.  They are however accessible to all which I believe is their real value to the community.

@mineZcash 
Our design for the Aion Foundation is locked to (210,9) and work would be needed to make a parameterized Equihash design which ZCash is based upon.   This would be used as a reference for the real work which would be researching our ideas on how to decentralize ZCash ASICs and creating a hardware solution, from an ASIC design perspective that would allow no single party control over processing power while maintaining privacy & security.

With the design being open sourced, one could decide to target an FPGA or ASIC, that is not up to me to decide but FPGAs allow us to quickly prototype solutions where simulation can only get us so far.

Switching to (210,9) would allow our team to focus solely on hardware methods to ensure ASIC decentralization and we believe there exists an elegant solution to this problem.  Without working with the protocol itself, we don't believe this can be done on our own.  The foundation has control over forking at will making any investment into hardware risky hence ePIC would only supply the hardware to the foundation and not sell to the consumer.  This ensures greed will not occur from our side and we can be reached via the normal legal channels.

Without going into our ideas, we believe if the foundation could embrace ASICs and create a model where they can be made available to all and I can finally upgrade my 480 without feeling like I'm getting ripped off.

@autotunafish
Agreed, there's hockey on tonight so back to the game for me.  Discussion is good even if this is not the path that will be taken. This ePIC proposal is only the beginning.

**Comment by autotunafish** [comment]
I dont agree with the way you leverage the community's heightened mentally distressed state to pitch your decentralized asic sale, its based primarily on our willingness to allow the fudsters to (conditionally) go on as they will and that is a waste of time, where in fact the contentious forking debates are needed and may be tiring (mentally) but not a waste of time

**Comment by Sto1cNate** [comment]
@earlmai what would be needed to configure one of the FPGAs to be compatible with parameters 144,5, which increases memory usage up to about 2.5GB? ZenCash is considering this as an option to maintain ASIC resistance in the short term.

https://blog.zencash.com/zencash-statement-on-potential-equihash-algorithm-change/

**Comment by earlmai** [comment]
@autotunafish honestly from presenting at Aionex, Bitmain releasing their ASIC and the grant being posted brought us here today. Finding a solution where ASICs can exist in the ecosystem may benefit ePIC but we are only researching the methods to do so and the community can decide on the path forward if we are involved or not. 

@Sto1cNate The change to (144,5) does not have a huge affect on the logic so we could still live in a low end FPGA setup.  As you mentioned the largest difference is memory usage and sadly a lot of the low end FPGAs either come with no memory or far less than that.  What's important is to determine how the Bitmain ASICs were designed. ie can their parameters be configured or are they fixed and is there a maximum memory limit each core has access to.  So I believe ZenCash should understand what they are trying to avoid before pivoting away.

**Comment by Sto1cNate** [comment]
@earlmai That is exactly what they're doing. Need to confirm the capabilities of the ASICs before making changes.
Could the FPGAs be configured to use high speed DDR4 memory? I have looked into QDR memory, but it looks like memory density isn't there yet to achieve 2.5GB at any affordable costs. Perhaps designs that utilize HBM style of memory could solve memory bandwidth/latency sensitive algorithms, otherwise high speed DDR4 looks to be a good price/performance compromise.

**Comment by earlmai** [comment]
@Sto1cNate FPGAs can be configured to use DDR4 but chip with HBM is hidesouly expensive and quite hard to get your hands on at the moment.  That being said, a memory controller/PHY is still needed which complicates things since they require a whole team to develop (Note they are typically licensed).  I believe Bitmain was going with 1GB DDR3 modules for another project and I would assume they are going for that approach this time around.

To keep the comments clean, feel free to email me

**Comment by mineZcash** [comment]
It should also be noted that there is a discussion about this taking place on the Forums too with perspective from Scott Howard (ePIC CEO) :  https://forum.z.cash/t/fpga-equihash-miner-developed-for-aion-network/28921

**Comment by kushti** [comment]
@earlmai do you think grant money would be enough to make an open-sourced ASIC design?

**Comment by earlmai** [comment]
@kushti a design would probably cost a bit more than that but you would get a functional design with not many optimizations.  Power, performance and area criteria are what separates a design from one another and requires much more work and man power.  This changes when targeting different process nodes and we have yet to cover the costs of wafers and masks.

**Comment by tromer** [comment]
The Zcash Foundation Grant Review committee has reviewed your pre-proposal, including the above discussion, to evaluate its potential and competitiveness relative to other proposals. Every pre-proposal was evaluated by at least 4 committee members .

The committee's opinion is that *your pre-proposal is not a leading candidate for funding in this round*, and the committee therefore does not invite you to submit a full proposal.
This decision is advisory, and you can still choose to submit a full proposal by June 15th, following the detailed structure described in the [Call for Proposals](https://github.com/ZcashFoundation/GrantProposals-2018Q2). Note that if the full proposal is substantially the same as discussion so far reflects, then it's unlikely to be chosen for funding; and if it isn't, then we encourage you to post a draft (or at least answer any open questions) as early as possible, to allow for community feedback. Regardless of your choice, we thank you for participation thus far.
