### ISSUE TITLE
Missing and Murdered Indigenous Women: OSINT Analysis and Mapping Project

### ISSUE THREAD

**Issue by SMPOTTRATZ** [ZcashFoundation/GrantProposals-2018Q2#23]
There is no standardized or official data collection regarding missing and murdered indigenous women. 
Current research indicates murder rates for indigenous women to be at least ten times the national average. 

Read more here:
https://indiancountrymedianetwork.com/news/native-news/missing-and-murdered-no-one-knows-how-many-native-women-have-disappeared/

Our project will perform OSINT analysis of missing and murdered women in the region of North and South Dakota. 

Our first priority is to provide maps for search and rescue organizations. 

My colleague and I have numerous requests for data coming from social workers, 
search and rescue, and other personnel who work against violence in their communities. 
We plan to expand our data set and create custom charts for these end users, and do so free of charge.

We have complete confidence in our ability to do this work because we already have a data set.
We are seeking the equivalent of $3,000 USD to expand our lab, and to train an indigenous data scientist on new software. We are donating our labor to this phase of the project.

Our projects relationship to the cryptocurrency community is one of bridge building, by demonstrating the societal benefits of cryptocurrency. Cryptocurrency driven projects can save lives.

**Gwen Lonewolf**: Bachelor of Science in Tribal Land Management, and Data Science, Master's Degree in Project Management. 

Gwen has extensive hands on experience in mapping geo physical data sets. Gwen is Lakota and a resident of the Standing Rock Reservation.

**Sarah Pottratz**: Physical Security, Maltego, Project Management, Front End.

**Comment by b-g-goodell** [comment]
This is an admirable project and should **undoubtedly** be funded by someone somewhere, but how is this idea in line with the Zcash foundation's stated mission?

**Comment by gcsfred2** [comment]
I think this project should be funded. 
I'd like to suggest for the scope of the project to include Canada, maybe at a phase 2. And I'm volunteering to link the project sponsors with Missing and Murdered Indigenous Women organizations in Canada.

In my opinion, the submission acts directly on the moral imperative of the ACM Code of Ethics written by the Association for Computing Machinery's Committee on Professional Ethics more directly  than any other that I've seen in the list. That imperative reads

"1. GENERAL MORAL IMPERATIVES.

As an ACM member I will ….

1.1 Contribute to society and human well-being.

This principle concerning the quality of life of all people affirms an obligation to protect fundamental human rights and to respect the diversity of all cultures. An essential aim of computing professionals is to minimize negative consequences of computing systems, including threats to health and safety. When designing or implementing systems, computing professionals must attempt to ensure that the products of their efforts will be used in socially responsible ways, will meet social needs, and will avoid harmful effects to health and welfare." [ http://ethics.acm.org/code-of-ethics ]

**Comment by b-g-goodell** [comment]
@gcsfred2 I agree that this project should be funded, and that it's clearly one of the more high-minded projects.

But the zcash foundation's mission is about internet payment privacy infrastructure. I can see a few angles one could take this project to fit into that framework. I'd like to hear a bit more from the pre-proposal authors about it.

**Comment by tromer** [comment]
Indeed, the scope of the Foundation's [Mission](https://github.com/ZcashFoundation/ZcashFoundation/blob/master/MISSION.md) is "building Internet payment and privacy infrastructure for the public good", and it cannot fund projects, no matter how noble and necessary, that are outside this scope.

**Comment by gcsfred2** [comment]
But wouldn't the proposed project be for the "public good"?

**Comment by SMPOTTRATZ** [comment]
It's true we are not building block chain technology, or a wallet, ect.

We applied under education and out reach. We are not obviously monetizable.

I have spent the last few weeks explaining crypto currency and zcash to a very interested tribal community.

We are examining how to release the core data set in a decentralized and transparent way.

We understand if we are considered out of scope for funding criteria. We are grateful to you for engaging in discussion with us.

Thank you for your time and consideration.

**Comment by SMPOTTRATZ** [comment]
@gscfred2 We discussed the possibility of us working on Canadian First Nations MMIW data. We are very interested in doing so. The scope of that work is considerable. They have no less than 5,000 victims. That is a huge project. We would need payroll funding and it would take some time. Ideally if we did this we would recruit data scientists from First Nations communities, and be able to compensate them. We would train them on our methodologies.

At any rate this project would be out of zcash scope.

If you want to further discuss this with us, my email is pottratzs (at) gmail.

**Comment by tromer** [comment]
The Zcash Foundation Grant Review committee has reviewed your pre-proposal, including the above discussion, to evaluate its potential and competitiveness relative to other proposals. Every pre-proposal was evaluated by at least 3 (and typically more than 4) committee members .

The committee's opinion is that *your pre-proposal is a promising candidate funding in this round*, and the committee therefore *invites you to submit a full proposal*.
Please submit a full proposal by June 15th, following the detailed structure described in the [Call for Proposals](https://github.com/ZcashFoundation/GrantProposals-2018Q2). We encourage you to submit a draft as early as possible, to  allow for community feedback.

**Comment by SMPOTTRATZ** [comment]
Thank you for considering our pre-proposal. Please find attached our full proposal below.

[MMIW.ZcashGrant.pdf](https://github.com/ZcashFoundation/GrantProposals-2018Q2/files/2101307/MMIW.ZcashGrant.pdf)

**Comment by sonyamann** [comment]
We regret to inform you that your submission was not selected by the Grant Review Committee, and hence the Zcash Foundation will not be funding this proposal. Thank you very much for your thoughtful contribution!

Please consider [subscribing to the Zcash Foundation newsletter](https://buttondown.email/zcashfoundation) so that you will be notified of future funding opportunities.

The Grant Review Committee’s comments:

> The proposal addresses missing and murdered indigenous women, suggesting link analysis and geophysical mapping against a data set provided by the community of Standing Rock.
> 
> The committee feels that the proposal is in not sufficiently related to the Foundation’s mission.
> 
> Funding of this proposal is not recommended.
