### ISSUE TITLE
A simplistic and user friendly payment system on top of Zcash for Emerging Markets

### ISSUE THREAD

**Issue by eddywm** [ZcashFoundation/GrantProposals-2018Q2#24]
(CLOSED)

**Comment by b-g-goodell** [comment]
Can you elaborate on the services your thin layer will be providing, the problems that the folks you want to help have been experiencing? I assume that the service you are talking about would also help merchants in other unbanked parts of the world too?

**Comment by eddywm** [comment]
Great question, the problems that many I have seen many businesses having can be subdivided into 3 points : 
 1 **The customer base and market size is really small** due to reasons that the unbanked are categorically excluded from buying products and services online.
 According to the latest World Bank statistics,In Africa only 27% are banked, in middle east it's only 17 %. 
The current financial infrastructure in these regions has failed and they don't have any ambition at all to bank the unbanked.

2 They are paying a lot of money in third party commission : Even for those businesses in the region that have integrated payment systems like PayPal are complaining on the fact that Paypal is charging a very big commission fee, and they have to not only support PayPal but all others like MasterCard, visa, mpesa, ... All of them are charging quite a lot per each transaction.

3. **Not support for micro-transaction** : For these types of market, it's really crucial to have support for micro-transactions since that may constitute quite a lot of the market segment. Local businesses are missing quite a lot.

The thin layer service that will provide will act like a glorified wallet mobile system for android & ios and a sophisticated backend  tuned to the needs and the realities of the local markets.
We are planning to build integration plug-ins for already existing businesses so that they can easily start using and taking advantage of the blockchain based payment system.

**Comment by tromer** [comment]
@eddywm Can you elaborate on your technical approach, and how it's different from other Zcash wallets?

**Comment by eddywm** [comment]
@tromer excellent question.

We realized that the wallets are designed to be generic and to work for everyone, that really couldn't work in our regions specifically.

The technical approach here will work like this:

Provide first direct integration of crypto payments to the online business itself, these are directly designed into their mobile applications and web apps. We built some prototypes for it and we showcased it for general e-commerces and musical platforms.
They all seemed to like the idea, it was at the Africa Blockchain Conference, where we even got to talk with many crypto engineers, we also got to talk with people from the Zcash the company who provided us even more insight for Zcash itself since it's among our top options. 

The addresses used into those integration plug-ins will be directly mapped into the wallets we plan to design so that the online businesses will be seeing the money entering in real time with no third party involved, in other words enjoying the flexibility of blockchain based solutions.


The last one is important, because it will act like a normal wallet but we'll design it with a customer centric approach in mind . We' ll work to provide local languages support and referral programs to even reach  out to more businesses and services.

Closing remarks. (A little bit out of the subject but important)
After the Africa Blockchain Conference which took place in the same city I live, we even now feel more confident to the success of crypto in the region since we got support of local regulators and they promised  us a sandbox execution like other countries.

**Comment by tromer** [comment]
What will be the functionality and API of these plug-ins?

What requirements are specific to your region and make generic wallets unsuitable?

**Comment by eddywm** [comment]
1. 
There will not be a common API for these plug-ins per se, it will be **depending on the specificities** of the software stack of the business wanting to make a crypto payment integration.

We plan to work with other dev teams for these plug-ins to work smoothly with existing applications.
The functionality will be mostly accept crypto payment, in details, on checkout a given id of the user session will be embedded in the qr code with the relevant cart details and the receiving address. 

2. 

1*. **The UI/UX** of current wallets and Zcash wallets in particular is somehow _suboptimal_. 
Most people specially new to crypto have come to expect simplistic and simple to use software, so the current design makes it hard for general mass adoption.
We have also to consider  that most people have not yet used online banking services in their lives.

2*. **The lack of local language support** for current wallets : After checking most of pre-eminent Zcash wallets, none provide support for **Swahili**  which is a vernacular language in the east African and central  region.

**Comment by tromer** [comment]
1. It's hard to evaluate your proposal to build plug-ins without any specific details about the systems, functionality, and your experience with these software stacks.

2a. Can you give examples of specific UX improvements you would make, compared to existing generic wallets?

2b. If you're only developing plug-ins, then you have  limited control over UX. 

3. If language is the rissue, wouldn't it make more sense to help localize an existing wallet, than to develop a brand new one?

**Comment by eddywm** [comment]
Please allow me to do a recap and a brief summary of our proposal and hopefully to be more clear for this time.


We recall one of the biggest problems we wanted to address was access to financial institutions, mostly about active bank accounts and the ability of people to do payments of products and services with the flexibility of new technologies, in general it was about economic exclusion problem.

The idea was to build first a payment system mobile app which is a wallet that abstracts most of the underlying blockchain technologies, thus make it more like a normal payment systems applications in terms of user experience. 

So to make it usable and maximise the adoption rate we had 2 main options:

**1 Support already existing applications.**

 Make simple integrations for existing online services apps. Technically acting like an intent (In Android terms ) started from the business’s application and launching directly the wallet with the important information needed for the payment passed to the wallet app to finalize the purchase.

**2 Build new platforms that will accept the payment system right away.**

Here we planned to build  a musical platform where musicians are paid in crypto directly to their  addresses, minimizing third parties and thus maximizing musician’s remuneration.

 The idea was once this type of platform goes mainstream, the adoption rate will finally happen based on power of influence of musicians in any communities. This was the part that I pitched in the conference.
The idea was to finally make crypto usable to everyday users and achieve the financial inclusion since the same payment system used to buy songs on musical platforms could be used on news platforms, e-commerces, ....

=================================================================================

`
1. It's hard to evaluate your proposal to build plug-ins without any specific details about the systems, functionality, and your experience with these software stacks.
`
Most of the existing businesses applications already expose a payment api  for payment without revealing the entirety of their software stack. So the knowledge of different is important but for a very tiny percentage of cases.

`
2a. Can you give examples of specific UX improvements you would make, compared to existing generic wallets?
`
- Reduce information overload to the user. (Most wallets bombard users with a huge amount of distracting and not needed information)

- Focus on basic roles of a wallet software, the extras functionalities should be op-tins.

- Some wallet's UI is entirely in mismatch with  look and feels of modern mobile operating systems.

`
2b. If you're only developing plug-ins, then you have limited control over UX.
`
The plug-ins side is different from the wallet side,  the wallet software will be entirely under our control and reason why we plan to make improvements on its UX

`
If language is the issue, wouldn't it make more sense to help localize an existing wallet, than to develop a brand new one?`
`
This is a good point, that's what could have been done if it was the only problem, but sometimes it makes sense to design from ground up and make more sane decisions and design considerations.

**Comment by tromer** [comment]
It seems that there are really three related but projects here:
1. Adding Zcash payment capabilities to some existing systems. Which ones and what are the concrete plans? Whose cooperation will you need to make this happen, on the technical side and real-world deployment side?
2. A Zcash wallet with a simple and streamlined interface for basic operations. We need more specific discussion to understand what changes you'll be making compared to good modern wallets and the [UX Checklist For Wallet Developers](https://z.cash/support/ux-checklist.html).
3. Language localization of some nice wallet.

**Comment by eddywm** [comment]
A good way to understand this proposal is to think about how a traditional  payment processor like PayPal or Stripe provides payment mechanism for E-commerces and services like Shopify, Deezer and others. 

But here the difference is all of these different compartments are blockchain based and thus take advantages of some of its properties like minimization of third parties, and mostly accessible for the unbanked  and and those systematically excluded from the financial services. (Which is the majority of the world population and the main reason of existence of this proposal)

1. `Concrete Plan` I think I have already talked about the approach in the previous posts.

2. `Collaboration Needed` Mostly for the business dev teams to streamline the integration and Zcash team for occasions where we may need deep insight from the protocol implementation.

3. ` technical side and real-world deployment side` A simple explaination will for instance, a musical platform selling songs and albums. On checkout a QR code with the singer address is prompted to the user, the user clicks clicks a button which opens the wallet send screen with the relevant information and then the user can finalize the transaction, the platform will monitor the blockchain for the publication of that transaction to approve the purchase.

**Comment by tromer** [comment]
The Zcash Foundation Grant Review committee has reviewed your pre-proposal, including the above discussion, to evaluate its potential and competitiveness relative to other proposals. Every pre-proposal was evaluated by at least 4 committee members .

The committee's opinion is that *your pre-proposal is not a leading candidate for funding in this round*, and the committee therefore does not invite you to submit a full proposal.
This decision is advisory, and you can still choose to submit a full proposal by June 15th, following the detailed structure described in the [Call for Proposals](https://github.com/ZcashFoundation/GrantProposals-2018Q2). Note that if the full proposal is substantially the same as discussion so far reflects, then it's unlikely to be chosen for funding; and if it isn't, then we encourage you to post a draft (or at least answer any open questions) as early as possible, to allow for community feedback. Regardless of your choice, we thank you for participation thus far.

**Comment by eddywm** [comment]
`
.. the committee therefore does not invite you to submit a full proposal.
This decision is advisory, and you can still choose to submit a full proposal ...
`
I don't understand, these 2 sentences seem contradictory to me, should I submit a full proposal even though my proposal was not << invited >>.

**Comment by tromer** [comment]
Yes, you can decide to submit a full proposal despite the above, and it *will* be considered.

**Comment by eddywm** [comment]
```
Note that if the full proposal is substantially the same as discussion so far reflects, then it's unlikely to be chosen for funding
```
Still I have not yet understood on which I was unclear, maybe you should help me the points you didn't understand so that I can give clarifications.
