### ISSUE TITLE
A statistical analysis of privacy in (private) cryptocurrencies

### ISSUE THREAD

**Issue by rbkhmrcr** [ZcashFoundation/GrantProposals-2018Q2#27]
## Motivation and overview

By applying clustering techniques and finding patterns in real-world use of
both Zcash and Monero, researchers have been able to
determine links between even supposedly private transactions. The anonymity
that these users may have thought they were getting and the anonymity they
actually achieved are at odds. Also, the future actions of other users have
the potential to influence the anonymity of transactions made by users who
followed the protocol exactly as they should.

We'd like to extend this research further to find out in what circumstances
this still applies, and whether it can be circumvented with, for example,
fine-tuned algorithms to select the distribution of inputs or even the timing of
transactions, in order to make the ecosystem as a whole more difficult to learn
from.

## Technical approach

We plan to do this by studying the transaction distributions in both Zcash and
Monero, creating simulations to see what sampling techniques work best with
real-world use, and presenting these results to the community in a way that
can be learnt from and built upon.

## Team background and qualifications

Team:
- [Sarah Meiklejohn](https://smeiklej.com/)
- [Rebekah Mercer](https://bekahoxoo.github.io/)
- [Claudio Orlandi](http://www.cs.au.dk/~orlandi/)

## Evaluation plan

Success in this case will take the form of an academic research paper, and tools 
to better reason about the concrete levels of anonymity achieved (and
achievable) by a cryptocurrency.

## Security considerations

If our findings impact the anonymity achieved by private transactions, we will
responsibly disclose them to the appropriate parties prior to publication, so 
that users have the opportunity to move their coins before we reveal any 
information.

## Schedule

- Potentially cluster private transactions (research and implementation);
- Construct a simulator to see if it is possible to better connect expected use
  of Monero/Zcash with the real-world use;
- Build a better view of what works in practice (simulation, definitions, etc).

## Budget and justification

The grant money would go towards covering the costs associated with research,
including computing power to analyse the existing blockchains and transaction
distributions and simulate alternative transaction/public key selection
distributions.

We expect to spend several months in total researching and implementing
clustering techniques; constructing and implementing the simulator; considering
how better to define anonymity in cryptocurrencies so it can capture what we
have learned.

## Email address(es) for direct contact

bekah at cs dot au dot dk

**Comment by tromer** [comment]
The Zcash Foundation Grant Review committee has reviewed your pre-proposal, including the above discussion, to evaluate its potential and competitiveness relative to other proposals. Every pre-proposal was evaluated by at least 3 (and typically more than 4) committee members .

The committee's opinion is that *your pre-proposal is a promising candidate funding in this round*, and the committee therefore *invites you to submit a full proposal*.
Please submit a full proposal by June 15th, following the detailed structure described in the [Call for Proposals](https://github.com/ZcashFoundation/GrantProposals-2018Q2). We encourage you to submit a draft as early as possible, to  allow for community feedback.

**Comment by tromer** [comment]
We have not received your full submission here by yesterday's deadline. Do you mean to withdraw your proposal?

**Comment by rbkhmrcr** [comment]
@tromer Yep, sorry if I was supposed to leave a note/comment saying so -- we're still planning on carrying out the project, but I don't have the capacity to make a document with the full proposal at the moment, and its existence doesn't seem too funding dependent. I'm excited to see everything else that's built with the grant money! :)

**Comment by tromer** [comment]
@bekahoxoo, thanks for the update, and I'm very glad to hear you'll carry out this project. If there's some way the Zcash Foundation can support this research or its publication in the future, please contact @acityinohio or me.
