### ISSUE TITLE
Add Zcash Support to the Anypay Merchant Payment System So That Customers Can Instantly Use Shielded and Transparent Zcash In Hundreds of Retail Stores With Zero Extra Effort to Businesses

### ISSUE THREAD

**Issue by derrickhorton** [ZcashFoundation/GrantProposals-2018Q2#28]
Imagine: You walk into your favorite restaurant, cafe, vape shop, theatre, gym, or concert venue, take out your phone, and pay for your meal, drinks, pipes, shows, and memberships -- all with shielded Zcash. You walk down main street and on every window there’s a fresh new sticker next to Visa and MasterCard: “Zcash Preferred Here.” 

If good money is supposed to be private, why is uber-trackable Bitcoin having all the fun? Why is the coin that the Feds are watching spreading like wildfire and the coin that actually acts like cash is nowhere? It is not your fault. No one has built the tools that merchants need to accept it.

Fear not. Zcash can be as fast and easy to use as a credit card. Not clunky and awkward but fun and cool. Yes, you will probably have to teach the person at the register how it works the first few times. But once you do, it will make the other cryptocurrencies look foolish by comparison.

“I can attest that the anypay app has done outstanding things for acceptance of DASH in Portsmouth. In the old days I used to go to places just to spend cryptocurrency. Now, I end up paying with DASH without making a special effort. One thing that is unique is the fact that merchants that use anypay actually are accepting dash. They are not using a payment processor that deposits dollars to their accounts. Merchants sometimes take their DASH and spend it with other merchants. This closes the loop avoiding the need to interact with the dollar economy.”
– _**Darren Tapp**, Dash Core Contributor_

100% of the world’s Zcash-accepting brick and mortar retail stores use Anypay. It is easy, secure, simple, beautiful, and fast. And it works with their existing hardware. No new devices, no complicated paperwork, no ID verification, no fees assessed to the merchant. Finally you have a free tool that will not only make your favorite store take your Zcash, it will make them LOVE you. Because in time, they will figure out that you are giving them a greater gift than they could have imagined: private, untraceable money right in their pocket.

Hundreds of merchants across America are already using Anypay to take private payments of cryptocurrencies. I have personally activated dozens of them. We at Anypay build relationships with these business owners and follow up regularly, asking about their everyday use and making improvements to build the best experience. They want something that will track how much the dollar value was when they took payment, and how much it is worth now. They want it to be stupid-simple to use so that even the dullest employee can figure it out without much instruction. They want to know instantly if the customer paid, and they want to know that their money is secure. We have done all that and more, and now we want to add Zcash to Anypay’s list of supported coins.

Our expert team of developers have decades of experience building professional-grade applications, and lead developer and CEO Steven Zeiler spent years as an engineer at Ripple. Adam Cmiel spent years in Silicon Valley at Lyft. Grant Jones worked as an engineer with Google full-time until last month when he devoted all of his time and attention to building Anypay. I, Derrick J. Freeman, have almost a decade experience in communications, specifically around cryptocurrency media production. We now lend all of our efforts to building the world’s greatest tool for bringing cryptocurrencies to retail stores, guided by principles of privacy, decentralization, and community.

What would you expect to pay for first-class shielded transaction support for the world’s most popular multi-coin crypto point-of-sale system? You might expect development this complex would easily cost 1,000 Zcash. And you would be right. The best developers are already working on exciting and high-paying products in the business world, and they demand fair reward to be pulled away to focus elsewhere. A single engineer could cost 500 Zcash easily to contribute to a project of this magnitude. 

We expected to ask for five times as much. But -- being heavily invested in Zcash ourselves, and because of our deep philosophical commitment to enhancing freedom for all people through financial privacy technology, we are willing to take an insane pay cut to develop this feature for the extremely modest sum of 100 Zcash. That is because we expect that by integrating shielded Zcash transactions into a rapidly growing merchant POS system, we will have a direct impact on the valuation of the coin. Making coins spendable is what we do, and the bottom line is that we want Zcash to replace credit cards. To do it, we need to know we are not alone. We need to know this matters to you. We humbly ask for your endorsement in the world’s most recognizable form: your financial commitment. Let’s do this.

**Direct Contact**
derrick@anypay.global

See an early demo of Zcash in use at the Free State Bitcoin Shoppe here:
[http://freestatebitcoin.com/2017/10/02/shielded-zcash-transaction-at-nh-retail-store/](http://freestatebitcoin.com/2017/10/02/shielded-zcash-transaction-at-nh-retail-store/)

See Anypay in use on CNN International:
[https://www.youtube.com/watch?v=KI7rKJgadhA](https://www.youtube.com/watch?v=KI7rKJgadhA)

**Comment by mineZcash** [comment]
So this request is to add support for Z-transactions on the existing Anypay app that currently on supports transparent addresses? 

Do you have details on the number of locations that use Anypay currently, and how many of them transact with Zcash?

What is the expected timeline for implementation? Before or after Sapling?

**Comment by derrickhorton** [comment]
Hey @mineZcash , thank you for the great questions. I am glad you asked.

Currently Anypay does not support transparent addresses for any merchants other than Free State Bitcoin Shoppe, which is in experimental stages and not yet ready for public release. This proposal, once passed, would give support for transparent and shielded transactions on the Anypay retail merchant POS so that customers and merchants would instantly see PAID screen upon payment. See the linked videos by CNN and the Bitcoin Shoppe for examples.

Currently there are hundreds of active accounts with Anypay. According to paywithz.cash, only 4 of them are locations that also take Zcash using their personal wallets. If this proposal were to be funded, all these merchants could automatically have Zcash activated so that customers can use transparent and shielded Zcash at the existing retail establishments without any extra effort.

Expected timeline for implementation is Summer 2018, over the next 2-3 months. Before Sapling in September. The experience would of course become even better after Sapling. We are very excited for that.

**Comment by tromer** [comment]
@TheDerrickJ, can you give us some quantitative estimates about Anypay's cryptocurrency transaction volume, and help us understand the type/mix of merchants?

**Comment by tromer** [comment]
@TheDerrickJ, may I suggest renaming this proposal to something more informative, such as "Add Zcash support theAnypay merchant payment system"?

**Comment by derrickhorton** [comment]
Hey @tromer , great questions. Thank you for asking about quantitative reports of Anypay's cryptocurrency transaction volume and the types of merchants using it.

In response to your question, we published the hard data revealing the amount of value (both in USD and BTC) passing through the platform, updated in real-time. You can see it here: [https://admin.anypay.global/#/charts](https://admin.anypay.global/#/charts)

As far as the types of merchants: There is no way of knowing all of the businesses using Anypay, but many are known. Among them include about ten dine-in restaurants, a yoga studio, a handful of coffee shops, several souvenir shops, a tattoo parlor, a brewery, a flower shop, several smoke/vape shops, a handful of sunglass & eyeglass stores (including optometry), a live theatre, a concert venue, a ballet studio, a hair salon, a ladies intimates apparel store, and a high-end vintage up-cycled clothing shop. 

The [Free State Bitcoin Shoppe](http://freestatebitcoin.com/category/blog/) showcases the dozens of businesses using Anypay in its small town of Portsmouth, New Hampshire with the [World Famous Bitcoin Tour](http://freestatebitcoin.com/tour/).

**Comment by derrickhorton** [comment]
@tromer Thank you for the suggestion to rename the title of the proposal to something more  informative. We took you up on the suggestion and hope you like it.

**Comment by tromer** [comment]
The Zcash Foundation Grant Review committee has reviewed your pre-proposal, including the above discussion, to evaluate its potential and competitiveness relative to other proposals. Every pre-proposal was evaluated by at least 3 (and typically more than 4) committee members .

The committee's opinion is that *your pre-proposal is a promising candidate funding in this round*, and the committee therefore *invites you to submit a full proposal*.
Please submit a full proposal by June 15th, following the detailed structure described in the [Call for Proposals](https://github.com/ZcashFoundation/GrantProposals-2018Q2). We encourage you to submit a draft as early as possible, to  allow for community feedback.

**Comment by derrickhorton** [comment]
Attached is our full proposal. We thank the Zcash Foundation for their consideration of funding Zcash integration into Anypay, the world's best retail crypto point-of-sale, as featured on CNN International.
[Full Proposal - Anypay.pdf](https://github.com/ZcashFoundation/GrantProposals-2018Q2/files/2107572/Zcash.Proposal.-.Anypay.pdf)

**Comment by tromer** [comment]
@TheDerrickJ, we are about to finalize the grant funding recommendations. Are there any updates in your status or plans that we should be aware of?

**Comment by derrickhorton** [comment]
@tromer Yes, there are some exciting updates since we last posted on this proposal a few months ago.  

First, our merchant network has grown to include over 800 accounts and expanded geographically to include North America, Europe, and Asia. Enabling these merchants to accept shielded ZEC would be totally sweet. 

Second, our Point-of-Sale app is now easier and more fun to use because it is mobile-first, so convincing merchants to accept ZEC is even easier. 

Our plans are to eventually put iOS and Android apps to the official stores so accepting ZEC at any business is as effortless as downloading Angry Birds.

Here is a video of how ZEC payments at retail works now:
https://www.youtube.com/watch?v=W0u7l66K7zY

Here a person is using ZEC to buy spicy mustard from a French wine and pastry shop:
http://anypay.global/2018/07/03/easy-step-by-step-instructions-to-take-bitcoin-and-digital-cash-at-your-business/

Empowering anyone to use shielded ZEC at retail stores is among the most radical things I can imagine. Cash is sadly still more private than bitcoin. Shielded ZEC is private, but it can not be used in real stores. Let us make that vision a reality.

**Comment by sonyamann** [comment]
I'm thrilled to inform you that the Grant Review Committee and the Zcash Foundation Board of Directors have approved your proposal, pending a final compliance review. Congratulations, and thank you for the excellent submission!

Next steps: Please email josh@z.cash.foundation from an email address that will be a suitable point of contact going forward. We plan to proceed with disbursements following a final confirmation that your grant is within the strictures of our 501(c)(3) status, and that our payment to you will comply with the relevant United States regulations.

We also wish to remind you of the requirement for monthly progress updates to the Foundation’s [general mailing list](https://lists.z.cash.foundation/mailman/listinfo/general), as noted [in the call for proposals](https://github.com/ZcashFoundation/GrantProposals-2018Q2#progress-reports).

Before the end of this week, the Zcash Foundation plans to publish a blog post announcing grant winners to the public at large, including a lightly edited version of the Grant Review Committee’s comments on your project. The verbatim original text of the comments can be found below.

Congratulations again!

Grant Review Committee comments:

> The proposer is made by Anypay, a Point of Sale gateway that allows Retail stores to accept Cryptocurrency as payment. They request funding to expand their infrastructure to enable Zcash payments.
> 
> This is an experienced team of developers and engineers who have worked for recognizable and reputable tech companies, and already have a working cryptocurrency point of sale which supports using other well-known cryptocurrencies, incl. Bitcoin, Dash and Litecoin. Unfortunately, as noted by the proposal, only four merchants out all of those that use Anypay take Zcash. If the plans in this proposal are achieved, Zcash payments will be accessible and simple for both users and merchants, enabling the PoS system and app to be configured to accept z-addresses, which will drive adoption and have significant long-term value.
> 
> The clear vision for the user interface is encouraging as it shows that commercialization is a real priority.
> 
> The Grant Committee feels that it is important to encourage the use of Zcash at Brick-and-Mortar stores and the Anypay system is capable of putting Zcash in more retail locations, and with support could expand beyond their current scale of retail locations.

**Comment by derrickhorton** [comment]
Thank you @sonyamann for the wonderful news! Our team is celebrating with sparkling water and big smiles. We are now brainstorming our strategy for tackling this exciting challenge. I will post monthly updates to the Foundation's general mailing list per the requirements to keep everyone informed of our team's progress, beginning immediately after the Zcash Foundation's public blog post announcement.

**Comment by mms710** [comment]
@TheDerrickJ Hi! I'd love to help provide any engineering support you might need from the engineers at Zcash Company. Would you be interested in getting a more regular line of communication set up between you and Zcash Company engineers so you can ask questions or get help? If so, would you be okay using a Rocketchat channel or do you have another preferred method of communication?

**Comment by sonyamann** [comment]
The grant has been finished! 🎊 https://anypay.global/shielded-zcash-at-retail/

I'm closing the issue.
