### ISSUE TITLE
New wallet designs for existing/ forthcoming builds

### ISSUE THREAD

**Issue by lugeb** [ZcashFoundation/GrantProposals-2018Q2#3]
In addition to the functional needs being addressed by devs, the UI for the existing Zcash wallet ecosystem is below consumer standards. While Zcash holders do enjoy the utility of third party wallets additionally, the current features of Zcash suggest that native wallets should be enhanced with an eye on extensibility towards additional future looking features.  The best utility + usability being the goal.

**Comment by mineZcash** [comment]
I agree this is a good goal, do you have recommendations for Developers to work on making this happen?

**Comment by tromer** [comment]
@lugeb, we will indeed need a lot more more information on your concrete suggestions and execution plan in order to assess your proposal.

**Comment by tromer** [comment]
The grant review committee needs further information, as discussed above, in order to evaluate your proposal.

**Comment by tromer** [comment]
The Zcash Foundation Grant Review committee has reviewed your pre-proposal, including the above discussion, to evaluate its potential and competitiveness relative to other proposals. Every pre-proposal was evaluated by at least 4 committee members .

The committee's opinion is that *your pre-proposal is not a leading candidate for funding in this round*, and the committee therefore does not invite you to submit a full proposal.
This decision is advisory, and you can still choose to submit a full proposal by June 15th, following the detailed structure described in the [Call for Proposals](https://github.com/ZcashFoundation/GrantProposals-2018Q2). Note that if the full proposal is substantially the same as discussion so far reflects, then it's unlikely to be chosen for funding; and if it isn't, then we encourage you to post a draft (or at least answer any open questions) as early as possible, to allow for community feedback. Regardless of your choice, we thank you for participation thus far.

**Comment by skyl** [comment]
I have a couple of things going with react-native here: https://github.com/skyl/react-native-zcash-wallet

**Comment by sonyamann** [comment]
No further discussion is expected on this issue, so I'm closing it.
