### ISSUE TITLE
Zcash App for Domestic Violence Victims

### ISSUE THREAD

**Issue by pkafei** [ZcashFoundation/GrantProposals-2018Q2#35]
**Introduction:**

[Nearly 3 women in the US are killed every day by domestic violence](https://www.nbcnews.com/news/us-news/domestic-violence-nearly-three-u-s-women-killed-every-day-n745166). The situation abroad is not any better. Studies show that about 35% of women experience domestic violence. These stats profile women specifically, but anyone can find themselves a victim of domestic violence. Regardless of the gender of the victim, addressing intimate violence is a human rights issue.

Many people observing domestic violence often wonder out-loud why the victim doesn’t immediately leave. There are many reasons why a victim cannot extract themselves from their dangerous situation, but money tops the list on why many people stay. [According to the National Coalition Against Domestic Violence](https://www.coindesk.com/women-on-the-block/l), 94% of women who experience domestic abuse also experience financial abuse.  Partners can use money as a way to control their victims. Specifically this looks like the abuser denying their partner access to a bank account, forbidding the partner to hold a job, or giving a partner an “allowance”.

**Zcash:**

Traditional banking and its KYI system makes it very hard for people experiencing financial coercion from their partner to take control over their own money and assets. It also makes it extremely difficult to receive outside financial help. 

Zcash, using zk-SNARKS, can allow for funds to discreetly be transferred to the victim. This initiative contains two parts. The main part is to design and deploy an app that social workers and victims could operate with ease. The second part of this initiative is to educate shelters on what is ZCash and how it can be used to help victims leave their hostile domestic situations and start the journey of becoming financially self-sufficient.

**Technical Approach**

We will build a mobile app that will allow women to hold and secure Zcash. This app will come with a how-to on what is crypto and what makes ZCash different from other cryptocurrencies like Bitcoin, and Ether.

There will be three stages of the project.

1. The first stage of this project will include outreach and educating shelters about cryptocurrencies. This will include an email campaign that will reach shelters in the United States and in other countries. Interested nonprofits will be invited to a series of live webinars. The nonprofits will answer a series of questions that will be a part of the user research phase.

2. We will start building the initial version of the application. The application will use [ZCash’s API](https://github.com/zcash/zcash/blob/master/doc/payment-api.md) and React Native. During this time period, we will send a newsletter to keep in touch with the participating organizations and there will be monthly community meetings via Google Hangouts.

3. The third stage of the project will include the gradual rollout of the application. There will be an open call for a review of the code- we’ll probably use something like [Bounty Source](https://www.bountysource.com/).

**Team and Expertise**

[Portia Burton
](https://www.blockchainexplainer.com/)
Portia Burton creates [blockchain prototypes for companies](https://www.blockchainexplainer.com/portfolio/).

Before she worked as a full-stack developer at the The Atlantic Magazine and worked as a machine learning developer at Trapit.

Portia also has a background in education and community development. She [creates accessible technical webinars](https://www.youtube.com/channel/UC6TMPPkN3ovziAxuVFLRobg/videos) about blockchain and speaks about blockchain at [major technical conferences](https://www.blockchainexplainer.com/about-us/).

**Comment by sonyamann** [comment]
Do you have a sense of how much funding you'd need for this project?

I think it would be critical to develop the app in partnership with social workers and/or DV survivors, to ensure that the end product would accommodate their specific needs.

**Comment by b-g-goodell** [comment]
I think the outreach to this community is vital. Can you elaborate on why a new app is necessary here rather than educating the community on zec-capable wallets like jaxx, etc?

**Comment by pkafei** [comment]
@sonyamann 

Thank you for responding to my proposal!

I'll be requesting $20,000. Here is a rough breakdown of the budget. 

Education and Outreach: $5,000

* Zcash and cryptocurrency webinars
* Distribution of newsletter
* How-to classes

Creation of the Zcash App: $15,000
* UX and usability research
* Wireframe
* Coding the application

I will be closely working with domestic violence organizations like [Battered Women's Justice Project](http://www.bwjp.org/services.html), and [Futures Without Violence](https://www.futureswithoutviolence.org/). In the near future, I plan on reaching out to more agencies. Domain knowledge experts of domestic violence will have a pivotal role in the shape and the direction of the app.

**Comment by pkafei** [comment]
@b-g-goodell

Good question! Wallets like Jaxx are great, but can be complicated to use for the uninitiated. The Zcash app for domestic violence victims will be designed with the unique needs of the target population in mind. Also, decent UX and content on 'how to use cryptocurrencies' on the application will scale the educational component of this project.

**Comment by amiller** [comment]
- Do you have current connections with Battered Women's Justice Project and Futures Without Violence? Can you elaborate on what working closely with them would involve?

- I think your proposed UX research activities are awesome, but I'm wary of putting a new app in the hands of a target population with very security-critical needs, without a lot of security engineering and analysis going into it first. Would it make sense to team up with any of the other wallet development proposals #3 #10 #43 #24  , or to scope your UX project so that it can be adapted into one or more of these wallets?

**Comment by pkafei** [comment]
@amiller Battered Women's Justice Project and Futures Without Violence is a sample of groups that will reach out to- which will be the first step of the proposal. 

I think you are right- security is paramount in building such an application. I will take a look at the suggested wallet development proposals. Thank you! 👍

**Comment by tromer** [comment]
I think that many attributes of this use case are shared with other privacy-critical settings, and so are best achieved in the context of a general-purpose wallet development (e.g., in collaboration with such an existing team, as @amiller) proposed).

What _technical_ requirements are unique to this use case?

How are the prospective _education and outreach_ activities unique to this use case?

**Comment by pkafei** [comment]
@tromer Haven't forgotten about your question! Will give you a detailed answer shortly.

**Comment by pkafei** [comment]
The Zcash wallet will have an interface where the user can:

* receive and exchange ZCash and Ethereum
* an API where user can exchange fiat currency for ZCash and Ethereum

Less is more with the domestic violence app. There will be no more than 2 cryptocurrencies and the  interface will focus on services and financial education pertinent to its target audience, something that would be harder to achieve with an all-purpose wallet.

For the education and outreach:

* There will be live online curriculum detailing what is a cryptocurrency and how it is different than fiat.

* How to use a cryptocurrency wallet

* General online security practices (using a VPN, Tor, and password management)

The first step in this proposal is to provide basic computer security information and general information about cryptocurrencies to the domestic abuse victims and their advocates.

**Comment by tromer** [comment]
The technical requirements you described are not unique to domestic violence victims. It's shared with much broader user demographies, perhaps with minor tweaks. It doesn't make sense to go through the effort of developing a wallet from scratch for this case.

Please consider changing the technical component of your proposal to working with existing wallets (which ones?) to help them better serve your use case. The education&outreach component makes more sense as tailored to the specific audience, but again can share a lot of education material with other efforts (e.g., see #30). The total budget would be correspondingly lower.

One consideration that _is_ pretty unique to domestic violence victims is the need to hide the _presence_ of the wallet from the abusive family member. There are several academic works and projects addressing this by methods hiding apps from cursory inspection by a non-expert.

**Comment by tromer** [comment]
The Zcash Foundation Grant Review committee has reviewed your pre-proposal, including the above discussion, to evaluate its potential and competitiveness relative to other proposals. Every pre-proposal was evaluated by at least 4 committee members .

The committee's opinion is that *your pre-proposal is not a leading candidate for funding in this round*, and the committee therefore does not invite you to submit a full proposal.
This decision is advisory, and you can still choose to submit a full proposal by June 15th, following the detailed structure described in the [Call for Proposals](https://github.com/ZcashFoundation/GrantProposals-2018Q2). Note that if the full proposal is substantially the same as discussion so far reflects, then it's unlikely to be chosen for funding; and if it isn't, then we encourage you to post a draft (or at least answer any open questions) as early as possible, to allow for community feedback. Regardless of your choice, we thank you for participation thus far.

**Comment by pkafei** [comment]
Thank you very much for reviewing my application. I agree that with the criticisms and will thoroughly address them before submitting a formal proposal.

**Comment by skyl** [comment]
I have a react-native harness that has a few APIs implemented here:

https://github.com/skyl/react-native-zcash-wallet

I'm implementing components and core functions outside of any application. So, you could add your application to the applications directory there and share in the work going into the components. My main initial focus is an OSX desktop app using react-native-macos. But, there is also an CRNA Expo harness setup to use components in the workspace.

**Comment by sonyamann** [comment]
No further discussion is expected on this issue, so I'm closing it.
