### ISSUE TITLE
Diversification across pools: Optimal mining strategies under PoW 

### ISSUE THREAD

**Issue by mysteryfigure** [ZcashFoundation/GrantProposals-2018Q2#37]
# **Motivation and Overview**

In a very recent work named “Decentralized Mining in Centralized Pools” [1], Jiasun Li (one of our team members) has been working towards analyzing the behavior of Bitcoin mining pools and how this affects the property of decentralization in cryptocurrencies (which is critical for their security). 

As part of this project we propose to extend their work to multiple PoW based cryptocurrencies (including ZEC) and eventually provide an automated tool for miners to optimally allocate their computational power in order to maximize their earnings based on their risk appetite. Since the optimal strategies involve diversification across multiple pools, they are expected to enhance PoW decentralization. 

Our goal is to provide a non-monetizable solution to help miners better allocate their hash rate which (for the great good) helps maintain the decentralization of PoW systems.

**Technical approach**

We plan to work on the following tasks: 

•	Extend the analysis of [1] to multiple PoW cryptocurrencies
•	Create an extended collection of top PoW cryptocurrencies (based on their market cap)
•	Create an extended collection of mining pools and their current payment policies and fees
•	Create an automated tool (to be publicly available for free) to guide a miner’s optimal strategy based on his or her computational power and risk preferences.

**Team background and qualifications** 

Foteini Baldimtsi, Assistant Professor of Computer Science at George Mason University
Jiasun Li, Assistant Professor of Finance, George Mason University

**Evaluation plan**

We will evaluate our method both mathematically and numerically. We will work towards optimizations so that our tool/engine gives answers in a reasonable time. 

**Security considerations**

As mentioned above the goal of the project is to promote decentralization of PoW based systems. 

**Schedule**

•	Collect data on PoW based cryptocurrencies, mining pools and mining pool reward policies. 
•	Extend the model of [1] to multiple cryptocurrencies
•	Create and test the automated engine
•	Publish the engine for free use.

**Budget and justification**

$20K

We plan to hire a graduate student to work on the research aspects as an RA for a semester (at a rate of $10K), a developer for both back and front end at the rate of ($5K) and we anticipate a cost of $5K for testing equipment and resources including some specialized mining hardware. 

**Email address(es) for direct contact**

jli29@gmu.edu 
foteini@gmu.edu

**Reference**
[1] Lin William Cong, Zhiguo He, Jiasun Li, “Decentralized Mining in Centralized Pools”, Working Paper, 2018, https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3143724

**Comment by tromer** [comment]
@mysteryfigure: For the convenience of community members who haven't read [1], can you please summarize its main analytical and empirical findings, and how they can realistically mitigate the problem of pool centralization?

**Comment by mysteryfigure** [comment]
@tromer Thanks for asking. If a miner directs all hash rates to a large pool, with the perception that a large pool better smooths income stream, pool concentration will be exacerbated over time. [1] proves that this widely held belief is incorrect. Indeed the best approach should be to diversify across pools (although it is non-trivial to determine the optimal diversification). With a tool that helps miners optimally diversify, large pools will no longer have advantages over small pools. Indeed, when further consideration about pool fee decisions are taken into account, pool sizes will tend to mean-revert, as demonstrated both theoretically and empirically in [1]. This mean-reversion tendency mitigates over-centralization among pools.

**Comment by tromer** [comment]
Can you offer an intuitive summary of the argument, given by [1], of why diversification is optimal, and what are the pertinent pool fee decisions?

(Unfortunately [1] doesn't seem to have a brief abstract or overview that explain this, and most people here, myself included, won't be reading the full paper right now.)

**Comment by mysteryfigure** [comment]
[1] studies how a miner should allocate his mining power and proves that a miner's reward will be maximized if the miner allocates his hash power over multiple mining pools (based on various criteria) instead of going for a single pool (even if this pool is the largest one, i.e. less risky).  

Why is this result important?
The result of [1] can encourage miners to look at multiple pools at the same time and eventually achieve higher decentralization of cryptocurrencies (since the tension to join larger pools will not be as high). 

What we propose here is to build a tool that will apply the results of [1] to a large of cryptocurrencies and mining pools. Using our proposed tool, a miner will input his total mining power (classified by specific by specialized hardware) as well as his risk aversion parameter and our tool will help miners to optimally diversify among different pools and coins.

**Comment by tromer** [comment]
The Zcash Foundation Grant Review committee has reviewed your pre-proposal, including the above discussion, to evaluate its potential and competitiveness relative to other proposals. Every pre-proposal was evaluated by at least 3 (and typically more than 4) committee members .

The committee's opinion is that *your pre-proposal is a promising candidate funding in this round*, and the committee therefore *invites you to submit a full proposal*.
Please submit a full proposal by June 15th, following the detailed structure described in the [Call for Proposals](https://github.com/ZcashFoundation/GrantProposals-2018Q2). We encourage you to submit a draft as early as possible, to  allow for community feedback.

**Comment by mysteryfigure** [comment]
Thank you for the good news. I'll send in a full proposal soon.

**Comment by bfoteini** [comment]
We are attaching our proposal here, thanks!
[Mining Strategies.pdf](https://github.com/ZcashFoundation/GrantProposals-2018Q2/files/2107508/Mining.Strategies.pdf)

**Comment by sonyamann** [comment]
We regret to inform you that your submission was not selected by the Grant Review Committee, and hence the Zcash Foundation will not be funding this proposal. Thank you very much for your thoughtful contribution!

Please consider [subscribing to the Zcash Foundation newsletter](https://buttondown.email/zcashfoundation) so that you will be notified of future funding opportunities.

The Grant Review Committee’s comments:

> This proposal addresses the crucial problem of pool centralization, with threatens the security properties of Nakamoto-style consensus, such as censorship-resistance and doublespend-protection, as well as the technical decentralization and economics of mining.
> 
> This proposal suggests to help miners choose pools in a way that optimally balances the expected mining reward (affected by pool fees) vs. the statistical variability of their income fees (affected by pool size). It claims that this would help combat pool centralization. Unfortunately, it's clear under what assumptions this is true; the discussions and references offered failed to clarify the point.
> 
> The budget seems excessive for the propsed work.
> 
> Thus, funding is not recommended.
