### ISSUE TITLE
PBS Endowment Fund

### ISSUE THREAD

**Issue by autotunafish** [ZcashFoundation/GrantProposals-2018Q2#4]
Hello my name is John Bruhling and I am a submitting formal grant proposal for the PBS Endowment Fund and/or a partnership with the PBS Foundation. The PBS Foundation is both a 501(c)(3) nonprofit organization and a 509(a)(3) supporting organization to PBS. 
I believe this would not only provide a unique, extremely effective, and generally appropriate means of advertising the Zcash Foundation, it would be beneficial to all current and potential Zcash users by investing in their public accessibility to the highest quality educational programming available.
The only drawback is the greatest extent of these benefits would be in the United States, although PBS International does distribute their programing throughout the entire world. 
PBS has been consistently, for the past 14 years, rated #1 in public trust among nationally know institutions. It is non-commercial and completely free to all Americans. I believe access and exposure to educational programming, especially at a young age, is vital for overall life-learning  and as such would benefit any current or potential Zcash users (or anyone) who would choose to watch it. I also believe this has a tremendous impact on the overall educational awareness and mental health of our communities and for theses reasons I believe an affirmative decision would fall within the scope of the Zcash Foundations values and mission. Its had a serious impact on my own life which is why I am submitting this proposal.
The amount granted, though without quota,  should be considered at least sizeable. No actual funds need transfered to me (or anyone else) outside of its execution requiring being performed by an outside party. I don't know the details regarding a Foundational partnership but would likely negate any need for that, if it existed.
Here are soem Copy paste statistics.

Over the course of a year, 80% of all U.S. television households - nearly 200 million people - watch PBS. The demographic breakdown of PBS' full-day audience reflects the overall U.S. population with respect to race/ethnicity, education and income. (Nielsen NPower, 9/19/2016-9/24/2017)

 Each month, over 90 million people watch their local PBS stations. (Nielsen NPower, 10/2016-9/2017)

 PBS averaged a 1.41 primetime household rating during the 2016-17 season, ranking it the #6 broadcast and cable network. (Nielsen NPower, 9/19/2016-9/24/2017)

 PBS' primetime household audience is significantly larger than many commercial channels, including A&E (the PBS audience is 135% larger), Bravo (126%), TLC (122%), Discovery Channel (70%) and HGTV (39%). (Nielsen NPower, 9/19/2016-9/24/2017)

 64% of all kids age two to eight - 18 million children - watched PBS during the 2016-17 season. (Nielsen NPower, 9/19/2016-9/24/2017, All PBS Stations, L+7 M-Su 6A-6A TP reach, 50% unif., 6+min.)

 PBS stations reach more moms with young children, and more Hispanic moms with young children,  than any other kids TV network. (Nielsen NPower, 9/19/16-9/24/17, L+7 M-Su 6A-6A TP reach, 50% unif., 6+min., LOH18-49w/C<6, Hispanic Origin. All PBS Stations, DSNY, NICK,  DSNYJr, NICKJr., SPRT, TOON & DISCFam)

PBS stations reach more chilren 2-8 in low-income homes, and more moms of young children in low-income homes, than any other kids TV network. (Nielsen NPower, 9/19/16-9/24/17, L+7 M-Su 6A-6A TP reach, 50% unif., 6+min., LOH18-49w/C<6, HH w/Inc<$25K. All PBS Stations, DSNY, NICK,  DSNYJr, NICKJr., SPRT, TOON & DISCFam)

PBS and stations provide the only free national 24/7 children’s TV channel and livestream, featuring more than 20 shows proven to improve kids’ learning. The service is available to more than 95% of U.S. TV households, reaching many children who may not attend preschool.
 
A national study of parents with children ages 2-6 found TV viewing is one of the top ways that families spend time together, with 89% of parents reporting they watch TV together as a family, 74% in favor of anytime access to educational programming and 37% ranking PBS KIDS as the best use of family screen time. (Maru/Matchbox, 2016)

Here are links to information cited, sorry if I didnt cover something! Thank you very much for your consideration and everything you do! John

http://www.pbs.org/about/about-pbs/overview/

http://www.pbs.org/foundation/who-we-are/

http://www.pbs.org/foundation/our-impact/

http://bento.cdn.pbs.org/hostedbento-prod/filer_public/pbsfoundation/assets/PBS%20Fact%20Sheets/PBS%20Facts%20Infographic.pdf

http://bento.cdn.pbs.org/hostedbento-prod/filer_public/value-pbs/Infographics/Top9Reasons.png

**Comment by amiller** [comment]
How would you get started on such a partnership? Would the idea be to produce a television show or documentary that is published via PBS? I'm not sure what kind of activities you have in mind but would like to hear more.

**Comment by autotunafish** [comment]
Im really not sure how that all works, and so very recently I have requested more information directly from them, I also referenced you so they may contact you as well

**Comment by autotunafish** [comment]
(Close issue button is way too big!)
There are various ways to give, I'm still waiting on a reply about general information but it seems fairly straightforward,
A non-cash security donation simply has a gift designation box to tell what the donation should go towards, such as a specific project or show, pbs Endowment fund (choosing which im not sure how, I know what I like but maybe a vote) It's created for traditional Investments and would need information about whether zcash would be accepted (considering it's traded on various stock trading platforms, I believe it probably would be), I will contact them about this presently
Credit donations are 1,2,3 so setting an exchange  zec/usd date/time and sending that could be a contingency.
There is also foundational and corporate partnerships, the ins and out of that im not sure and would probably require foundation members speaking to them. 
Also Im not sure about the tax implications and benefits of deductibility and such would fall on myself acting as an escrow instead of a inter-foundation partnership

**Comment by autotunafish** [comment]
Here is information of areas of focus and current initiatives, perhaps a voting system like Helios could be used at least for a generalization if nothing so specific http://www.pbs.org/foundation/areas-of-focus/

**Comment by tromer** [comment]
The Zcash Foundation Grant Review committee has reviewed your pre-proposal, including the above discussion, to evaluate its potential and competitiveness relative to other proposals. Every pre-proposal was evaluated by at least 4 committee members .

The committee's opinion is that *your pre-proposal is not a leading candidate for funding in this round*, and the committee therefore does not invite you to submit a full proposal.
This decision is advisory, and you can still choose to submit a full proposal by June 15th, following the detailed structure described in the [Call for Proposals](https://github.com/ZcashFoundation/GrantProposals-2018Q2). Note that if the full proposal is substantially the same as discussion so far reflects, then it's unlikely to be chosen for funding; and if it isn't, then we encourage you to post a draft (or at least answer any open questions) as early as possible, to allow for community feedback. Regardless of your choice, we thank you for participation thus far.

**Comment by autotunafish** [comment]
Thank you very much for your consideration, I'm sorry I was unable to post more information as they have yet to respond but if they do within reasonable time I will share with you regardless! Thank you!

**Comment by sonyamann** [comment]
No further discussion is expected on this issue, so I'm closing it. Thanks John!
