### ISSUE TITLE
Poster Art Series promoting Zcash and Financial Privacy

### ISSUE THREAD

**Issue by hloo** [ZcashFoundation/GrantProposals-2018Q2#40]
## Motivation and overview

 Visual art can be an effective tool for conveying an idea or message. For-profit companies are adequately incentivized to create visual art (for example, print advertisements and video commercials) for marketing their goods and services, but they are not adequately incentivized to create visual art aimed at educating the public on matters related to the public good. Non-profits, like the Ad Council, often step in to fill the gap, helping to fund and develop visual art for "public service announcements." The non-profit Zcash Foundation can play a similar role, funding visual art to promote ideas and messages central to the Foundation's mission. (As part of its form 1023 submission to the Internal Revenue Service, the Foundation stated that it will "educate the public regarding cryptocurrency through a variety of potential means.")

The goal of this proposal is to develop a series of posters (similar to the World War II home front posters developed in many different countries during the 1940s) to educate the public about the importance of financial privacy and promote Zcash as an important tool for achieving financial privacy in the future.

The end product will be a series of posters, suitable for printing and framing, downloadable for free from the Foundation's website. The Foundation will be free to disseminate printed copies of the posters if it so chooses.

## Technical/Logistical Approach

Artists will be contacted and selected based on evaluations of their prior work related to poster art. Commission fees will be negotiated, along with contractual terms that ensure that the Foundation will be free to disseminate the posters as the Foundation sees fit. To reduce artist commission fees, the artists will be free to also sell prints of their commissioned work on their own websites.

If applicable, permission to use the Zcash trademarks on the posters will be obtained from the Zcash Company.

The posters will be designed and published one poster at a time, so the Zcash community at large can give feedback and influence the design of later posters.

## Team background and qualifications
The team will consist of one lead, Howard Loo (a software developer and attorney with no artistic skill, but with experience in collecting art, including vintage poster art), working in conjunction with one or more graphic artists that have proven backgrounds in poster art. Howard Loo will take no compensation for this project. **All grant money will go towards commissioning the art, so all the grant money will go to the artists.** Furthermore, any cost-overruns will be covered out of pocket by Howard Loo.

## Evaluation Plan
Although artistic quality is in the eye of the holder, the goal is to create posters on par with the quality of the [fantasy travel posters](https://www.jpl.nasa.gov/visions-of-the-future/) published by NASA's Jet Propulsion Laboratory (but not necessarily in the same style).

A potential metric of success is the number of times that the digital posters are download. Another potential metric of success is the number of printed posters disseminated.

## Security Considerations

Not applicable.

## Schedule

The first poster will be published no later than August 1, 2018, with the rest of the posters following one at a time. The last poster will be published no later than December 1, 2018.

## Budget and justification

$2,500, which will cover several posters. As mentioned above, 100% of the funding will go to the artist commissions. Any left over funding will be donated back to the Foundation in full.

## Direct contact

Howard Loo can be contacted via [forum.z.cash](http://forum.z.cash) (username: hloo) or [chat.zcashcommunity.com](http://chat.zcashcommunity.com) (username: hloo).

**Comment by sonyamann** [comment]
+1 to this idea — having more visual materials to promote the Foundation and its goals would be useful for my work in particular. We could repurpose the poster artwork for events, merch, etc. To that end it would be good to have the artists provide large-scale printable files, e.g. 24" x 36", 300dpi.

I like this aspect of the proposed plan: "To reduce artist commission fees, the artists will be free to also sell prints of their commissioned work on their own websites." It would also help seed the ecosystem, which is an explicit purpose of our grants program.

In terms of the legal arrangement, IMO it would make the most sense to have the artists do a work-for-hire. The Foundation would own the copyright, but then we would release the artworks under an [Attribution 4.0 International (CC BY 4.0) license](https://creativecommons.org/licenses/by/4.0/), for use by the community.

Alternately, we could grant a commercial license to the individual artists in order to sell prints, but more broadly release the artworks under a _non_commercial license. However, that severely constrains what people can do with the IP.

A potential concern would be how, or whether, to coordinate this project with the Foundation's internal branding efforts.

**Comment by hloo** [comment]
@sonyamann Thank you so much for this feedback. I will take a look at the license that you referenced; it sounds like it could be a good fit. Also, I agree that it is essential for the digital files to be usable for large prints. If possible, we'll require that the artists provide vector-based art files so that the files can support large prints.

**Comment by tromer** [comment]
The Zcash Foundation Grant Review committee has reviewed your pre-proposal, including the above discussion, to evaluate its potential and competitiveness relative to other proposals. Every pre-proposal was evaluated by at least 3 (and typically more than 4) committee members .

The committee's opinion is that *your pre-proposal is a promising candidate funding in this round*, and the committee therefore *invites you to submit a full proposal*.
Please submit a full proposal by June 15th, following the detailed structure described in the [Call for Proposals](https://github.com/ZcashFoundation/GrantProposals-2018Q2). We encourage you to submit a draft as early as possible, to  allow for community feedback.

**Comment by hloo** [comment]
Here is the full proposal; thank you so much for considering it.

[poster_art_grant_proposal.pdf](https://github.com/ZcashFoundation/GrantProposals-2018Q2/files/2107667/poster_art_grant_proposal.pdf)

**Comment by sonyamann** [comment]
I'm thrilled to inform you that the Grant Review Committee and the Zcash Foundation Board of Directors have approved your proposal, pending a final compliance review. Congratulations, and thank you for the excellent submission!

Next steps: Please email josh@z.cash.foundation from an email address that will be a suitable point of contact going forward. We plan to proceed with disbursements following a final confirmation that your grant is within the strictures of our 501(c)(3) status, and that our payment to you will comply with the relevant United States regulations.

We also wish to remind you of the requirement for monthly progress updates to the Foundation’s [general mailing list](https://lists.z.cash.foundation/mailman/listinfo/general), as originally noted [in the call for proposals](https://github.com/ZcashFoundation/GrantProposals-2018Q2#progress-reports).

Before the end of this week, the Zcash Foundation plans to publish a blog post announcing grant winners to the public at large, including a lightly edited version of the Grant Review Committee’s comments on your project. The verbatim original text of the comments can be found below.

Congratulations again!

Grant Review Committee comments:

> Proposed by Howard Loo, a Zcash advocate who wants to create Zcash awareness through Art and Media. His proposal seeks funding to pay professional artists to create a series of posters to educate the public about the importance of financial privacy and promote Zcash as an important tool for achieving financial privacy in the future.The end product will be a series of posters, suitable for printing and framing, downloadable for free from the Foundation's website. The Foundation will be free to disseminate printed copies of the posters if it so chooses. The Grant Review Committee thought this proposal was clear and the amount requested is reasonable for original high quality artwork. Most felt that this would be a low-risk proposal with the potential to create some nice promotional materials to advocate for the use and adoption of Zcash. Full funding of this proposal is recommended.

**Comment by sonyamann** [comment]
Completed: https://www.zcashposters.com/
