### ISSUE TITLE
Documentary Film

### ISSUE THREAD

**Issue by natkramermedia** [ZcashFoundation/GrantProposals-2018Q2#41]
## INTRODUCTION
My name is Nathaniel Kramer. I am an independent media maker, emphasizing film and video, and I have been a cryptocurrency enthusiast since 2013.

In 2016, after expressing to Zooko my interest in his team's efforts, I had the opportunity to work as an independent contractor for the Zcash company, making the Denver station media recordings of the first MPC paramgen Ceremony. Later, these recordings contributed to WNYC's Radiolab program called The Ceremony that aired in July 2017, as well as other media that have since made their way out to the world.

In addition to the sound recordings that were featured in the Radiolab piece, we were also rolling video for some of the preparation, as well as for the first Ceremony itself.

## MORE RECENT WORK ON THIS PROJECT
Since that time I have conducted 3 interviews with Zooko (as well as accompanying him to a decentralized technology conference), one with a key Zcash engineer and one of the architects of the ceremony, and I have several more interviews and a plan to attend Zcon0 actively in the works.

## GOALS
*What's going to be achieved?*
* One of two main goals is to construct a final, polished piece that could be shared widely, and might be of interest to a broader, non-technical audience. 

Presently, I am most interested in making a film that features Zcash, The first Ceremony, and my current thought is to conclude with Powers of Tau and the new MPC to show a kind of movement towards further decentralization.

Points to be covered will include:
1. An 'on-ramping' (explanation for a non-technical viewer) to blockchain technologies & decentralization.
1. The invention of Zcash and how it was brought into existence--the cooperation and effort of various interesting personalities.
1. The special characteristics of Zcash within the blockchain space.
1. Practical and philosophical aspects of privacy in our contemporary world, and some historical context.

With this in mind, the final format and channels of distribution will be chosen. As stated above, presently, I am keen to emphasize a traditional film format. However, I feel open to anything from a feature with an aim toward a festival circuit run and traditional distribution, to a traditionally-formatted television program, to web episodes, to a give-away. For example, The Pirate Bay: Away From Keyboard ultimately gave away their final film, appropriately enough, over BitTorrent. The overarching goal is for the product to gain wide exposure.

* The other main goal is to make recordings (particularly interviews) available sooner than a finished, edited piece. This could be done by posting pieces online with a popular video service site (YouTube or Vimeo) or via a simple webpage that could host the content. This would be much easier to achieve, and would require only a tiny fraction of the editing time and management needed to make a final film, and could benefit the community to the extent people are interested in unedited material.

## RIGHTS
*Who gets to use or make something out of these materials?*

My intention is to release any raw recordings I make under the Creative Commons Attribution, Non-Commercial license. This would allow others, without permission, to freely distribute, annotate, and remix these materials; but not to derive profit from them. ie, Disney could not take these materials and create a for-profit piece; but someone could make a different film from the same materials if they did not sell it, or sell advertising around it.

I would certainly consider other licensing schemas, if this would assist the project in moving forward.

## FUNDING
*What would you do with a grant?*

I already have all the gear I'm expecting to need, which includes production and post-production gear. That leaves:
###### Primary costs:
* Travel expenses to conduct interviews / go to an event or two. [I have already arranged travel to Zcon0. I have applied and I hope to get a 'press pass' to document these proceedings.] Some of the other destinations where desirable interviews could be conducted are: NYC, DC, Toronto, San Francisco, Illinois. $4k.
* Editing & Post Production: I would work for 4 months (~16 40 hour weeks; 640 hours, about $25/hour) for 16k.
###### Secondary costs:
* Media licensing: This could include helping to get excellent music and stock footage. This can make a big difference in a final product. $3k.
* Finalizing: The finishing touches. It is a good practice to bring in specialized professionals, if at all possible. $5k.
* Marketing / Distribution: I don't want to spend an enormous amount on this, but some small budget would probably help meet costs associated with getting it out the door and into the public view. $1k
* Production & planning time: volunteer, no cost.

Total proposed amount is $29k. Funding could also be broken up into two or more cycles--for example; one for production and one for editing.

For reference, TPB:AFK raised about $80k total, and took about four years to complete. Many quality documentaries can run into the hundreds of thousands or even low millions to produce.

## PROFESSIONAL QUALIFICATIONS
*Why Should you be trusted to make something good? Or finish this project at all?*
* I am an experienced media maker: I've worked as a producer, editor, videographer, sound engineer, music director, broadcaster and animator.
* I have intimate knowledge of the production pipeline, from planning all the way through production, editing, and finishing.
* I have experience and a successful track record in 'landing the plane.' The danger of stalling and project abandonment is extremely high in media because of the time and resources required to complete an ambitious project. A proper candidate for this type of project would have a demonstrable record of dedication, tenacity, and assiduousness.
* I have worked for folks who have been Academy Award-nominated, Emmy and Grammy award-winners--that is to say, I have a perspective on and drive for quality products.
* I have a passion for independent media as well as social engagement. I believe mass communication is a critical point where the rubber of knowledge and technology meets the continuous road of collective culture. In short, I am in it for the action.

## MEDIA TRACK RECORD
*What have you done before?*
* Editing three festival-award-winning films.
* Producing/filming/editing a pitch which was a Kickstarter Staff Pick.
* Contributing to a nationally-syndicated radio show.
* Producing/filming/editing a television program aired on PBS.
* Contributing camerawork to a DVD included in the deluxe edition of a platinum-selling record.
* Blogged about on Huffington Post and Laughing Squid.
* Working on media supporting several successful ballot initiatives.
* Broadcasting and producing for years on award-winning independent radio.
* Portfolio: https://www.natkramermedia.com/portfolio/
* Finally, I have an animation I just completed that I am proud of--but I can't post it publicly yet! Let me know if you'd like to see and I'll send a private link. I'd like the next one to be about the blockchain!

## TANGIBLE MILESTONES
*When will this stuff happen?*
* PRODUCTION COMPLETION : Estimated November 2018.
* POST : Already begun, ramping up upon completion of production, estimated November 2018 - May 2019.
* FINISHING : Target for completed film: June 2019.

## CONCLUSION
So far, everything since October 2016 has been an independent, non-commercial effort--I've spent a considerable amount of time and a fair bit of money to get to this point, and I'd like to continue developing this story. It's large (and distributed!) so having some resources to bring to bear would help bring this project to fruition. With a grant of this type, I could devote myself full-time to this project.

More information/clarification available on request. Let me know what you think & best of luck to everyone involved in all your pursuits!

**Comment by rex4539** [comment]
What's "the director's approach" on the subject? What's the angle?

For example, is this a strict, clean cut, TV style documentary or a modern, visually intriguing take on Zcash that aims to blow the audience's socks off?

Do you have a treatment or script for this?

Could you provide a comprehensive list of storyline points in order to get a better understanding of the storytelling?

**Comment by natkramermedia** [comment]
Thank you for your questions and consideration.


> What's "the director's approach" on the subject? What's the angle?
> For example, is this a strict, clean cut, TV style documentary or a modern, visually intriguing take on Zcash that aims to blow the audience's socks off?

This project is an on-the-ground attempt to capture reality, supplimented by interviews done in a typical question and answer/conversational format. In this way, I would say the closest broad category is called Direct Cinema. For a general, historical context I suggest this brief reading:

https://en.wikipedia.org/wiki/Direct_cinema

One important difference is that I am not explicitly interested in questioning ... "the relationship of reality with cinema," per se--I hope to make something that will illuminate some of the potentially difficult-to-understand topics involved, without muddying the waters with some kind of meta-framework *about* film making.

Essentially, I am interested in bringing the events, personalities, technologies and philosophies into the foreground--for those who do not know about such things; to bring the present into the real.

There may be elements that are integrated for aesthetic or informational reasons that do not fit directly into the two categories mentioned above--possible examples might include; an animation to explain the blockchain, a piece of music to set an emotional tone, a piece of stock footage or a historical recording that was not captured by my camera to suppliment or increase the scope of the film, and so on.

I do not intend to utilize a narrator as a storyteller or voice of authority--though this technique can be very useful, so I do not want to absolutely rule out such a device.


> Do you have a treatment or script for this?

Not yet; documentaries are often made as the project is edited from the pool of available material. What is said by the people who are recorded will be the script; and recording is a process still underway.


> Could you provide a comprehensive list of storyline points in order to get a better understanding of the storytelling?

Essentially the points are broadly outlined under 'goals,' in my pre-proposal above. I don't have a lot I can easily add at this time--certainly not comprehensively--much will be determined by what material is gathered. However, I would be happy to compile a more detailed list of points if that would be desirable, if this project is interesting enough to evaluate in detail.

However, I would like to clearly but respectfully add that I am not interested in accepting this grant if it is to mean that some subjects or storyline points are to be emphasized or de-emphasized, approved or disapproved.  My aim is not to make a promotional piece, nor an attack piece--but to spotlight this fascinating subject with openness and honesty, style and integrity, and try to relate a story that I, with my own admittedly limited and subjective perspective, would view as being truthful and accurate, evocative and thought-provoking.

I feel with the foundation's assistance, I could also add timely to the above criteria.

**Comment by alc-nmff** [comment]
Thank you for your proposal. Can I ask you what's your motivation and inspiration to embark on this project? What is the main idea of the movie? What will you attempt to show to the audience?

**Comment by natkramermedia** [comment]
>  Can I ask you what's your motivation and inspiration to embark on this project? What is the main idea of the movie? What will you attempt to show to the audience?

Put briefly; my inspirations for embarking were a strong interest in decentralized technologies, the phenomena of money and cooperation in human culture in a broad sense, and later, more concepts surrounding privacy.

One of my main motivations was/is to explore this contemporary topic and bring some things I find worthy of consideration into the public sphere with an 'accessible' media product--that is to say, assuming an audience of reasonable intelligence and some attention, that some relevant information could be communicated, and some reflection could be provoked.

I'd like to show some events that have happened in recent history (largely, the first MPC and Powers of Tau) that were documented. It is my belief that these events will provide an interesting glimpse of things happening in this space to a general audience, and provide a kind of launching point for further discussion.

I think also that society in general is beginning to understand more about the importance of these topics (or at least discuss them more), so I feel this document could be part of a timely movement towards understanding/appreciation.

One other thing I would like to add is that some years ago I worked as a media maker for a climate scientist in association with a national (US) science research lab--while these programs aren't something I'm currently showing off in my portfolio (available on request), communicating science is something I've had some practice with; and getting the facts about the technology accurately communicated--even if they are somewhat simplified--is something I will insist on.

Finally, the animation I mentioned above has now been released, so if anyone is interested to see some of my motion graphics works, even on a totally unrelated topic, please feel free to to check that out now on my portfolio page, FWIW!

Thank you again for your time and consideration.
-Nat

**Comment by tromer** [comment]
The Zcash Foundation Grant Review committee has reviewed your pre-proposal, including the above discussion, to evaluate its potential and competitiveness relative to other proposals. Every pre-proposal was evaluated by at least 3 (and typically more than 4) committee members .

The committee's opinion is that *your pre-proposal is a promising candidate funding in this round*, and the committee therefore *invites you to submit a full proposal*.
Please submit a full proposal by June 15th, following the detailed structure described in the [Call for Proposals](https://github.com/ZcashFoundation/GrantProposals-2018Q2). We encourage you to submit a draft as early as possible, to  allow for community feedback.

**Comment by natkramermedia** [comment]
[NKM-Full-Proposal.pdf](https://github.com/ZcashFoundation/GrantProposals-2018Q2/files/2107714/NKM-Full-Proposal.pdf)

**Comment by sonyamann** [comment]
We regret to inform you that your submission was not selected by the Grant Review Committee, and hence the Zcash Foundation will not be funding this proposal. Thank you very much for your thoughtful contribution!

Please consider [subscribing to the Zcash Foundation newsletter](https://buttondown.email/zcashfoundation) so that you will be notified of future funding opportunities.

The Grant Review Committee’s comments:

> Proposed by Nat Kramer, a media maker. He proposes a documentary about Zcash, the first Ceremony, and conclude with Powers of Tau and the new MPC, depicting a movement toward further decentralization.

> The committee felt that the proposal was incomplete, lacking structure and storyline that would help understand the narrative from the director’s specific point of view.

> Funding of this proposal is not recommended.

> The committee does recognize the proposer as an able media maker and encourages him to discuss a new proposal with the Foundation, for the creation of small educational videos around Zcash. The proposal can either have the form of an ongoing support from the Foundation or it could be submitted as a new proposal when the next round of grants are announced.
