### ISSUE TITLE
Education: Zcash workshops and hackathons with CS students in northeast of Brazil

### ISSUE THREAD

**Issue by gcsfred2** [ZcashFoundation/GrantProposals-2018Q2#42]
Motivation and overview

The idea of the project is to host two workshops about Zcash in the northeast of Brazil, at one of the public universities open to low-income Computer Science students. In many public universities in Brazil,  a number of positions in undergrad programs are reserved for low-income students. The northeast of Brazil, in turn, is one of the areas with lowest quality of life indices in the country (https://brasilescola.uol.com.br/brasil/a-regiao-nordeste.htm , https://brasilescola.uol.com.br/brasil/o-idh-no-brasil.htm , http://hdr.undp.org/sites/all/themes/hdr_theme/country-notes/BRA.pdf ).
The motivation is to share the knowledge of Zcash's technologies with students with two workshops. After that, two hackathons will explore applications of Zcash that may offer social benefits to the communities of the students (such as banking, private messaging, payment systems, or other systems that the students may think of). The workshops will include optional assignments. The expected long-term impacts are
a) to empower these low-income students to continue in the development of such systems, possibly with the collaboration of the global Zcash community.
b) to allow more communication and collaboration between individuals of different economical contexts in the global Zcash community.
c) to provide an opportunity for students to continue researching and working with Zcash.
The instructor (aka project lead) will publish a report to the Foundation on each milestone of the schedule.
A minimum of 8 committed students will be required for the workshops and hackathons to happen before Milestone 1 of the project.

Technical approach
The workshops and hackathons will refer to the latest documentation and Zcash software. All resources produced by the instructor and the students will be shared with the Zcash community (it is foreseen that most of the material will be in Portuguese). A requirement for students to participate in the project  is that all software and design created will be open source.

Team background and qualifications
Gustavo Frederico is a Senior Software Architect. Even though Gustavo doesn't have yet a lot of experience with Zcash, he does have some experience with Bitcoin and Ethereum. Gustavo also participated in Zcash's Powers of Tau ceremony. See also https://www.linkedin.com/in/gustavofrederico/ . ( CV will be attached )

Evaluation plan

We will provide an anonymous evaluation sheet to students and we'll publish the results publicly. 
If successful, the project 
a) will have taught theory of blockchains and theory of Zcash (with references to papers, documentation and code).
b) will have a set of (mini) open source projects that will be created by the students  (may include source code and/or design. There must be an abstract in English.)
c) will have encouraged students to continue their research on Zcash or Zcash-related fields (privacy, anonymity, identity, distributed systems, blockchains, cryptography, zk-SNARKs, etc)
d) will have opened the possibility for some low-income students to work with Zcash or Zcash-related fields in the future.

What would your project look like if successful, and how would we be able to tell? Include quantifiable metrics if possible.

Security considerations

N/A 

Schedule

Milestone 1: Content of workshops are prepared
Milestone 2: Content of hackathons are prepared
Milestone 3: Resources such as classroom for the sessions in Brazil are reserved
Milestone 4: Logistics for travel are reserved (airplane tickets, hotel)
Milestone 5: Workshops 1 and 2 are complete
Milestone 6: Hackathons 1 and 2 are complete
Milestone 6.5: (1 week after Milestone 6) Possible follow-up with each group via Skype/Hangout
Milestone 7: (target: 1 week after Milestone 6.5) Versions "0.1" of mini-projects that are the result of the Hackathons are online (Github likely)
Milestone 8: Final report published

The actual dates of in-locus workshops and hackathons may vary depending on the university schedule. Milestone 1 to 7 must be less than 30 days.

   Possible schedule in-locus in Brazil:
Day 1: Workshop 1 - possibly 7 hours
Day 2: Students work on assignment #1. ( The instructor will be accessible. )
Day 3: Workshop 2 - possibly 7 hours
Day 4: Students work on assignment #2. ( The instructor will be accessible. )
Day 5: Hackathon 1 - possibly 4 hours
Day 6: Hackathon 2 - possibly 4 hours

Budget and justification

Airplane tickets: ( more details to come )
Hotel:   ( more details to come )
Food for trainer, transportation:   ( more details to come )
Honorarium for trainer: 15 000 USD
Classroom rental:   ( more details to come )
Food for students during training:   ( more details to come )
Transportation aid for students: 500 USD

Email address(es) for direct contact

gcѕfr𝔼d at ցmail dot com

**Comment by techoluwoye** [comment]
Gustavo this sounds really interesting! Doing previous work and research in Brazil think it will be very beneficial in South America. Will the workshops have a language preference ? Delivered in Portuguese or English?

**Comment by gcsfred2** [comment]
Hi, techoluwoye, the contents of the workshops will be in Portuguese and will be delivered in Portuguese. For the hackathons, in turn, students will be encouraged to produce source code and documentation in English, but if they cannot, Portuguese will be accepted, with the exception of the abstract which must be in English.

**Comment by techoluwoye** [comment]
Sounds good!!

**Comment by tromer** [comment]
What would be some examples of projects?

What do you expect as the cost per participant? I'm worried that this will be very high, for an education/outreach effort that's not focused on deliverables.

**Comment by gcsfred2** [comment]
There would be no charge for the students. 
I'd like to add more details to the hackathon projects before Milestone 2, but these would be preferably applications of Zcash related to payments, identity, wallets, zk-SNARKs and possibly applications of zk-STARKs. I may also ask for feedback from different fora on the hackathon projects.

**Comment by tromer** [comment]
@gcsfred2, I meant the cost per participant for the Foundation.

It is hard to evaluate the plausibility of execution, the difficulty of finding suitable students, and the value of the deliverables, without discussing specific candidate projects at some length.

**Comment by tromer** [comment]
The Zcash Foundation Grant Review committee has reviewed your pre-proposal, including the above discussion, to evaluate its potential and competitiveness relative to other proposals. Every pre-proposal was evaluated by at least 3 (and typically more than 4) committee members .

The committee's opinion is that *your pre-proposal is a promising candidate funding in this round*, and the committee therefore *invites you to submit a full proposal*.
Please submit a full proposal by June 15th, following the detailed structure described in the [Call for Proposals](https://github.com/ZcashFoundation/GrantProposals-2018Q2). We encourage you to submit a draft as early as possible, to  allow for community feedback.

**Comment by tromer** [comment]
We have not received your full submission here by yesterday's deadline. Do you mean to withdraw your proposal?

**Comment by gcsfred2** [comment]
Yes, I'd like to withdraw my proposal.

**Comment by sonyamann** [comment]
No further discussion is expected on this issue, so I'm closing it.
