### ISSUE TITLE
Guarda Zcash Wallet iOS

### ISSUE THREAD

**Issue by cytns** [ZcashFoundation/GrantProposals-2018Q2#43]
## Guarda application for Zcash foundation grants 2018Q2
We are a group of blockchain enthusiasts with background in software development and product management. We have a distributed team from EU, Russia and Ukraine. At the moment we have experts from IT, fintech, blockchain, security, marketing, design, UI/UE.

We develop mobile cryptocurrency wallets which would make using any cryptocurrency easy, accessible and secure. Recently we developed [Guarda Zcash Wallet](https://play.google.com/store/apps/details?id=com.guarda.zec) (Android) and [open source SPV library](https://github.com/guardaco/zcash-SPV) with a GP-2017Q4. Good experience could be developed further and Guarda is pleased to participate once again in this grant proposals.

Our background in developing a wallet solution for T-addr and cooperation with foundation will help us implement all necessary functionality and follow Zcash approach with the focus on security and productivity. Also we will enrich Zcash wallet with additional features such as: instant exchange; Zcash purchase for fiat; sell options. 

Guarda has acquired European FIU license for fiat-to-crypto exchanges (reg. number: 14320990). This license lets us provide best rates and conditions for all types of fiat-to-crypto operations and extend the number of services in our wallets.

## Technical approach
We are developing light wallet which means that user private keys are always under the user control. The private keys are always on the customer device and managed only by user. The wallet signing a transaction on the device side and transmit the signed transaction over Internet using ssl to blockchain node.

### We are guided by several core principles:

- Building trustless solutions.
If customer wants to rely on other cryptocurrency node he\she can type in this information.

- Multicurrency approach.
We thoroughly choose best cryptocurrencies and willing to support them all.

- Respectcustomers privacy.
We do not require any KYC or customers data when dealing with crypto. No registration for crypto operations is required as well.

- Never touch customers funds.
The proposed wallet is a light wallet allowing customer manage his\her keys himself

- Never touch fiat.
Purchase of cryptocurrencies will be delivered in collaboration with professional payment gateways.

### In general the wallet consists of the following parts:

- Server side node
Blockchain community developed solution. Open-source and distributed free

- Lightwallet library
This allows you to work with the cryptocurrency blockchain, without the additional overhead of having to write your own integration code for the platform. Usually the library interacts with the server side node through JSON RPC. As we are applying for a grant we believe this part of our work should be open sourced and available for public on a royalty free basis.

- GUI layer
Customer experience oriented graphic user interface running on mobile operating system of the mobile phone.

High level architecture can be described as follows:

![guardazcashios](https://user-images.githubusercontent.com/15582487/40263032-b35e11a0-5b15-11e8-979c-a14bf60f0227.jpg)

### We have three basic stages for the wallet implementation.

- Everything starts from the own blockchain nodes deployment. We have own primary and backup nodes for the wallet support. In addition we offer a range of third party nodes that can be applied by user. We are using sophisticated proxy for the node balancing in order to get up-to-dated blockchain status.

- The next step is mobile client library implementation. It is used by mobile wallet to manage transactions and abstract blockchain, security, cryptography layer from GUI developers.

- The last stage is the design implementation of mobile application. We are thriving to use trendy and cozy interfaces in our wallets to provide best customer experience.

- We are developing light wallet which means that user private keys are always under the user control. The private keys are always on the customer device and managed only by user. The wallet signing a transaction on the device side and transmit the signed transaction over Internet using ssl to blockchain node.

### The Guarda wallet implemented functions are:

- Send coins
- Receive coins
- Display the wallet history
- Transaction details
- Exchange cryptocurrencies (zcash<>crypto)
- Import/Export the private key
- PIN code app protection

### To be implemented in following two months (before Zcash wallet to be released):

- Purchase zcash for the fiat
We’ve integrated a number of fiat/payment providers (including Coinify) and more partnerships are on the roadmap. The full list of partners is available on [guarda.co](https://guarda.co).
- Other node usage
- Mnemonic phrase
- Z-address implementation

## Team background and qualifications

- Paul S., CEO, has three years experience in blockchain, 10 years in fintech. Certified banking cards security and business expert. Launched over 6 successful projects within last three years. Paul interests are: cryptocurrency exchanges, wallets, smart contracts, oracles.
- Eugene I., CPO, has 5+ experience in IT product management, 8+ years in UX/UI, a user-focused crypto evangelist, blockchain specialist
- Alex N., senior iOS developer, 7+ years of mobile development, qtum, zcash, decent library development
- Nikita P., graphic designer, 5+ years in Web and Mobile design
- Roman L., senior backend developer, expert in blockchain, has 3+ years of experience for blockchain development, cryptocurrency mining, qtum, zcash, decent library development

## Evaluation plan

We have quite tiny and reasonable schedule for the wallet implementation. The distributed team with a variety range of professionals gives us ability to launch in the parallel main project phases: blockchain node deployment, mobile library and wallet GUI development.

We are using agile approach with continuous delivery, so in any time of moment we are ready to present our progress and performance to the Grant Review Committee.

## Security considerations

Security is our priority. The light wallet approach itself is our vision for the secured blockchain wallet. The customer private keys are the most important and sensitive aspect.

We store keys in iOS secure storage in an encrypted form.

We are using additional product features to increase the product resistance for the attacks. The team has already implemented PIN-code for the wallet access.

At the node side we are using network security tools, like a WAF with ML.

## Schedule

We are estimated the whole zcash wallet duration as 12 weeks:

- **1 week** hosting & node setup, UE
- **2 week** node proxy, setup net security tools, mobile library, UI mock ups
- **3 week** mobile library for t-address development, UI prototyping
- **4 week** mobile library for t-address development, UI design
- **5 week** mobile library for z-address development, mobile app implementation, UI prototyping
- **6 week** mobile library for z-address development, mobile app implementation, UI design
- **7 week** integration with third parties services, mobile app implementation
- **8 week** mobile app implementation
- **9 week** alfa release, QA, bug fixes, mobile app implementation
- **10 week** QA, bug fixes, beta-release
- **11-12 week** Project Risks worked

## Budget and justification

We have estimated preliminary costs estimation for 30K USD for the project that will cover almost all issues.

[Web site](https://guarda.co/)
[Github](https://github.com/guardaco)
[Twitter](https://twitter.com/GuardaWallet)
[Medium](https://medium.com/guarda)
[E-mail](mailto:hello@guarda.co)

## Contact

Please contact @anna-spada with any questions or concerns

**Comment by rex4539** [comment]
Do I understand correctly that by the time this project is delivered, the Sapling upgrade will be released, which will make the remote proving service for shielded transactions redundant?

**Comment by cytns** [comment]
Please contact @anna-spada with any questions or concerns.

**Comment by anna-spada** [comment]
@rex4539 Sorry for a prolonged silence. Coming back to your question: our main objective is to deliver a library that anyone will be able to use for building Zcash apps.
Also our service will support not only z-addr but t-addr as well for they are being used on mobile quite actively!

**Comment by tromer** [comment]
The Zcash Foundation Grant Review committee has reviewed your pre-proposal, including the above discussion, to evaluate its potential and competitiveness relative to other proposals. Every pre-proposal was evaluated by at least 3 (and typically more than 4) committee members .

The committee's opinion is that *your pre-proposal is a promising candidate funding in this round*, and the committee therefore *invites you to submit a full proposal*.
Please submit a full proposal by June 15th, following the detailed structure described in the [Call for Proposals](https://github.com/ZcashFoundation/GrantProposals-2018Q2). We encourage you to submit a draft as early as possible, to  allow for community feedback.

**Comment by anna-spada** [comment]
Hello Eran!
Thanks for your email. I’m just a bit confused with the suggestion to submit a full proposal. If you could tell me what information is missing, I’ll be happy to make all necessary additions. 


Thanks!

Anna

**Comment by tromer** [comment]
@anna-spada, please review point 4 in the  [Call for Proposals](https://github.com/ZcashFoundation/GrantProposals-2018Q2), but yes, your pre-proposal is already close to that.

**Comment by tromer** [comment]
We have not received your full submission here by yesterday's deadline. Do you mean to withdraw your proposal?

**Comment by anna-spada** [comment]
Hello!
I’m sorry for being late for the deadline, we had to make changes to the schedule: initial evaluation in 12 weeks turned out to be too optimistic. Z-addr development will presumably take more time, given that Sapling release might impact significantly.
Please find the final proposal attached. Hopefully we still have a chance to work on Zcash iOS wallet!



Thanks and Regards
Anna

**Comment by tromer** [comment]
@anna-spada, I don't see any file attached. Can you please add it ASAP?

**Comment by anna-spada** [comment]
Second try. 
[Guarda application for Zcash foundation grants 2018Q2.pdf](https://github.com/ZcashFoundation/GrantProposals-2018Q2/files/2114581/Guarda.application.for.Zcash.foundation.grants.2018Q2.pdf)
Thanks

**Comment by AntechIndia** [comment]
Are you looking forward to developing a wallet along with exchange? Well, we have mastered in Bitcoin and Ethereum application development and we are eager to spread our expertise and proficiency with best-in-class **cryptocurrency wallet development** solutions. We are fully compliant with strict regulatory standards central to the financial industry and payments.

Hire our wallet app developers who build big web and mobile application as per the client requirements while following the key agile methodology. We make sure that your project gets delivered in the iterative build so that your regular feedbacks continuously get integrated into the app. Fill in the form and get a quick response from us.

Website : https://antiersolutions.com/cryptocurrency-exchange-development-company.html
Skype is : exchange@antiersolutions.com
Email us : info@antiersolutions.com
Contact us : 98550 78699

**Comment by tromer** [comment]
@eugeneives, we are about to finalize the grant decisions, but meanwhile noticed that the Guarda Android wallet apps have disappeared from Google's Play Store. What's the status of your wallet project, and of this proposal?

**Comment by cytns** [comment]
@tromer Hello! I quit Guarda.
She will be able to answer your question > @anna-spada

**Comment by anna-spada** [comment]
Hello everyone!
@tromer  About a week ago Google Play has unexpectedly deleted all our apps from the market (apparently due to some policy update). So we have made a decision to open-source all our apps and make them available for download on our site (www.guarda.co). 
We’re working on it now and I’ll keep you updated. Hopefully, all the apps will be there within one week. 
Also, we have reached out to Google, trying to get the apps back on the Google Play.
Stay tuned!

**Comment by ni23457** [comment]
https://www.reddit.com/r/btc/comments/9f1jvn/russian_changelly_atomic_wallet_changenow_guarda/

**Comment by tromer** [comment]
@anna-spada Any news on your open-source release and the Google Play status?

**Comment by guardawallet** [comment]
@tromer In 2-3 weeks we are launching Mobile Multi-currency Wallet, that will be available in Google Play. All 15 Guarda Single-currency Wallets are open source now and available at https://github.com/guardaco/guarda-android-wallets

**Comment by sonyamann** [comment]
We regret to inform you that your submission was not selected by the Grant Review Committee, and hence the Zcash Foundation will not be funding this proposal. Thank you very much for your thoughtful contribution!

Please consider [subscribing to the Zcash Foundation newsletter](https://buttondown.email/zcashfoundation) so that you will be notified of future funding opportunities.

The Grant Review Committee’s comments:

> The proposer, Guarda, has developed a Zcash t-address Android wallet under a prior Zcash Foundation grant, and have open-sourced it. They propose to also develop an iOS wallet.
> 
> While they have delivered on their previous promise, we don't see the point of funding a t-address iOS wallet at this time. We would support funding an iOS wallet with support for z-addresses. However, experience with the previous grant awarded to Guarda, for an Adroid wallet, shows this is unlikely to happen unless shielded-light-wallet libraries are readily available to Guarda; but while these are under development by ZcashCo, it may take months for them to be available.
> 
> Thus, we believe the optimal course of action is for Guarda to await the shielded-light-wallet libraries from ZcashCo; using these, add z-address support to their Android wallet (as they committed to in the previous grant awarded to them); and then develop and iOS wallet using those same libraries.
> 
> Thus, we do not recommend funding this proposal at this time, but suggest that the Zcash Foundation fund this effort (in a future grant proposal or outside the Grants program) when the requisite dependencies become available.

**Comment by mms710** [comment]
@eugeneives Hi! I'd love to help provide any engineering support you might need from the engineers at Zcash Company. Would you be interested in getting a more regular line of communication set up between you and Zcash Company engineers so you can ask questions or get help? If so, would you be okay using a Rocketchat channel or do you have another preferred method of communication?

**Comment by cytns** [comment]
@mms710 Hi! I quit Guarda. Please check with @anna-spada or @guardawallet

**Comment by mms710** [comment]
Oops sorry! @anna-spada @guardawallet please let me know if you'd like to set up a communication path with Zcash Company engineers for help on your project!

**Comment by guardawallet** [comment]
@sonyamann thank you for considering our proposal! We are happy to continue supporting the community anyway.  
By the way, currently we are working on z-addresses, and it will be available in all Guarda wallets very soon.

**Comment by guardawallet** [comment]
@mms710 thank you so much, it is very appreciated! The best way for us would be a Slack channel I believe. Is this communication method convenient for you?
