### ISSUE TITLE
PayWithZ.cash

### ISSUE THREAD

**Issue by ezvaughn** [ZcashFoundation/GrantProposals-2018Q2#6]
# **PayWithZ.cash**

## **Motivation and overview**
When introducing someone to any cryptocurrency, a question they invariably ask is - “Where can I spend it?”   The objective of PayWithZ.cash is to answer that question.   I expect the site to serve as a critical resource for the community and to help accelerate usage of Zcash.       

## **Technical approach**
I built PayWithZ.cash on a free, ad-supported hosting service, Hostinger.    Using this service is a good way to get the info on the internet at low cost, but there are factors that could be improved, such as eliminating advertisements, improving the design, and reducing off-line time.    Paying for professional hosting and professional web design will elevate the user experience.    
Risk factors include merchants on the site not actually accepting Zcash, or failing to continue to accept it over time.   Connecting with the community via my @paywithzcash twitter page will help identify merchants who accept Zcash.  Verifying acceptance with actual purchases as well as follow up on acceptance will be critical.  Identify, verify, and re-verify.

## **Team background and qualifications**
I’ve been following Zcash since the inception in October 2016; I’ve been mining and running a node since 2017; and I built PayWithZ.cash in February 2018.       

## **Evaluation plan**
As Zcash grows in usage and acceptance, PayWithZ.cash will grow with it.   
- Number of merchants accepting Zcash will increase.  There are currently 29 merchants listed on PayWithZ.cash.
- @PayWithZcash twitter followers will increase.  There are now 26 twitter followers. 

## **Security considerations**
The site is for information purposes only.   A disclaimer about not endorsing or evaluating listed merchants is at the bottom of the main page.   Also, there are no plans of monetization with advertisements or paywalls.   

## **Schedule**
With the current amount of merchants, they can be plainly organized under category headers such as clothing or restaurants.     I anticipate it would take 30-40 hours to complete a professional website design.  Merchants will be added to the site continually as they are discovered.  
In the future, as more merchants accept Zcash, and as resources allow, I’d like to add a merchant locater map, a general search box for quick references, and individual merchant pages with user reviews.

## **Budget and justification**
$1k to $3k    

_Ad-free hosting service.  $125-360 (0.5-1 ZEC)._ 
- Option A:  HostGator is $8/month for a standard plan, so $288 will pay for 3 years of ad-free hosting.   HostGator hosts over 600,000 websites. 
- Option B:  A2 hosting is $9.99/month for a swift plan, so $360 will pay for 3 years of ad-free hosting.   A2 hosts over 200,000 websites and is ranked highest in load time speed.
- Option C:  Eliminating the advertisements on the current host, Hostinger would be $3.49/month for a 3 year plan, so $125 will pay for 3 years. 

_Re-skin site on professionally hosted service.  $700 (2-3 ZEC)_
I will re-skin the current website myself with WordPress.   I estimate this would take 30-40 hours of my own work with consultations from web designers as needed.     

_Professional web design.   $0-3,000 (0-12 ZEC)_
Hire a web designer, complete the initial re-design, and make necessary iterations.   
- Option A:  AIO Group is my preferred designer.  I know them from past work and am confident they can help make a beautiful, uncluttered, and professional design.   AIO Group services are between $85-100 per hour.    They do have a backlog of a few months before they could start on a new project.
- Option B:  Jack Leonard (http://jackleonard.me/) is a designer/developer from Ireland and is passionate about privacy and encryption.  He has worked on a number of Dash projects and has been designing for blockchain companies for 4 years.   His work has been featured in WIRED, Forbes Magazine, Mattermark & The Irish Times.   After looking over this project, he estimated it would take approximately 40 hours for a total fee of 10.5 ZEC or 0.33 BTC ($2,500).  
- Option C:  Creatable (https://creatable.co.nz/) is a boutique graphic design agency in New Zealand.   They are listed on the dash.org/merchants site as a web designer.  I spoke with Sarah Narayan at Creatable, and she would like to work on the project.   She is familiar with cryptocurrencies and what we are trying to do.  She prefers to use the Devi Wordpress theme, although is open to making it as simple or as complicated as we wish.  

## **Email address for direct contact**
Email: eric@paywithz.cash

**Comment by mineZcash** [comment]
What are your future plans for the website? Are you planning on monetization with advertising?

**Comment by omisekawa** [comment]
My only purpose in creating PayWithZ.com is to help accelerate the acceptance of Zcash.    There are no plans to monetize.

**Comment by amiller** [comment]
In my opinion "accelerating acceptance of Zcash" is not (on its own) a reason that fits well enough for the Foundation's mission. One reason is that it's something that everyone holding Zcash has an incentive to do, so it's not something that the non-profit needs to stimulate. However, an independent website tracking places that accept Zcash could be useful for other reasons besides that.

Is there a process to get listed on the website? Do you have a plan to periodically check in on whether the sites listed are still active / still accepting Zcash?

**Comment by omisekawa** [comment]
When I identify a business accepting ZCash I try to verify it before I include them on the site.   And yes, I agree that there should be follow up on merchant acceptance.

**Comment by derrickhorton** [comment]
This collection of info is critical. I do cryptocurrency outreach every day. Showing that there are real places to spend Zcash demonstrates to others that it is a *currency* and not just another token. It has features and a reason for existing: privacy. That's a big reason the vape shop in my town (listed on your site) takes it. I see this site growing to becoming a major resource for Zcash enthusiasts, including interactive maps like some of the other coins have done to show you where you can spend near you (CoinMap, DiscoverDash, etc).

@amiller (accelerating acceptance of Zcash is) "something that everyone holding Zcash has an incentive to do, so it's not something that the non-profit needs to stimulate." 

I hear you. You're right. Consider this: Is everyone who's holding Zcash actively working to accelerate its acceptance? Is it 90%? 50%? It's probably more like 20% if you follow the 80/20 rule, and it may be much less than that.

Given this thought experiment, how much faster could Zcash become widely used if the Foundation did incentivize stimulation? Is the request by @ezvaughn a modest amount if it could increase adoption by 1%? 

People people who are building tools to benefit Zcash users, if empowered, can make our favorite cryptocurrency a real-life medium of exchange everywhere. I appreciate the efforts he's already put into his merchant locator tool and look forward to seeing what he can produce with a little bit of funding.

**Comment by b-g-goodell** [comment]
I think this is probably in line with the foundation's mission statement: building Internet payment and privacy infrastructure for the public good, primarily serving the users of the Zcash protocol and blockchain. I am not sure if an actively curated list of merchants is technically infrastructure, but if not, then neither is the Google Maps functionality in searching for a local hardware store or coffee shop or whatever.

I am a little skeptical of claims about accelerating adoption, though, it seems accessory to the point. The existence of a directory like this won't necessarily make it easier for zcash users to persuade their landlords to accept rent in zec, for example.

**Comment by derrickhorton** [comment]
@b-g-goodell : "The existence of a directory like this won't necessarily make it easier for zcash users to persuade their landlords to accept rent in zec."

Respectfully, what could possibly do more to persuade a landlord to accept Zcash than to show them where they can use it? In my experience setting up dozens of retail stores to accept cryptocurrency, nothing is as effective at driving adoption as pointing to the other places that accept it. Invariably, "Where can I spend it?" is the first question they ask.

**Comment by b-g-goodell** [comment]
Landlords don't spend their rent money at Walmart or Amazon, they use it to pay off their mortgages. Verizon doesn't care if they can use your cell phone bill at a nice little italian restaurant that accepts zcash. Etc. Respectfully.

A small business owner is more likely to look at this site and say "aha, I can use this at Home Depot," sure, and such a website would be valuable... But I don't think the primary attraction here would be to accelerate adoption so much as to provide a veritable "yellow pages" for zcash.

**Comment by omisekawa** [comment]
In the early 1900s the Michelin tire company wanted to accelerate the use of car tires, so they made a guide of restaurants that were worth driving to, and some of them may have been nice little Italian restaurants.   The Michelin Guide made a lasting impact on both the usage of car tires and on restaurant visits.

**Comment by sonyamann** [comment]
I concur that websites like this are key for community outreach and development of a robust user ecosystem. It'd be worth including "dark web" ecommerce options along the lines of Dream Market as well, although perhaps that would be too controversial?

**Comment by omisekawa** [comment]
That is definitely something worth considering, although I have no knowledge of the dark web so it would be difficult for me to verify those merchant options.

**Comment by tromer** [comment]
@ezvaughn, can you say more about your intentions to expand the site? What new information or process will it include?

Feel free to attach sketches.

BTW note the related page https://github.com/ZcashFoundation/ZcashFoundation/wiki/Organizations-that-accept-Zcash-donations .

**Comment by omisekawa** [comment]
With the current amount of merchants, they can be plainly organized under category headers such as clothing or restaurants.

**Comment by tromer** [comment]
The Zcash Foundation Grant Review committee has reviewed your pre-proposal, including the above discussion, to evaluate its potential and competitiveness relative to other proposals. Every pre-proposal was evaluated by at least 3 (and typically more than 4) committee members .

The committee's opinion is that *your pre-proposal is a promising candidate funding in this round*, and the committee therefore *invites you to submit a full proposal*.
Please submit a full proposal by June 15th, following the detailed structure described in the [Call for Proposals](https://github.com/ZcashFoundation/GrantProposals-2018Q2). We encourage you to submit a draft as early as possible, to  allow for community feedback.

**Comment by tromer** [comment]
We have not received your full submission here by yesterday's deadline. Do you mean to withdraw your proposal?

**Comment by ezvaughn** [comment]
[GrantProposals-2018Q2 · GitHub 2.pdf](https://github.com/ZcashFoundation/GrantProposals-2018Q2/files/2108216/GrantProposals-2018Q2.GitHub.2.pdf)

**Comment by sonyamann** [comment]
I'm thrilled to inform you that the Grant Review Committee and the Zcash Foundation Board of Directors have approved your proposal, pending a final compliance review. Congratulations, and thank you for the excellent submission!

Next steps: Please email josh@z.cash.foundation from an email address that will be a suitable point of contact going forward. We plan to proceed with disbursements following a final confirmation that your grant is within the strictures of our 501(c)(3) status, and that our payment to you will comply with the relevant United States regulations.

We also wish to remind you of the requirement for monthly progress updates to the Foundation’s [general mailing list](https://lists.z.cash.foundation/mailman/listinfo/general), as originally noted [in the call for proposals](https://github.com/ZcashFoundation/GrantProposals-2018Q2#progress-reports).

Before the end of this week, the Zcash Foundation plans to publish a blog post announcing grant winners to the public at large, including a lightly edited version of the Grant Review Committee’s comments on your project. The verbatim original text of the comments can be found below.

Congratulations again!

Grant Review Committee comments:

> The proposer is Eric Vaugh, the developer of PaywithZ.cash website which is a community run website which lists merchants and stores that accept Zcash for payment. This currently a very basic one-page website with poor design and hard to read formatting. Eric would like to update this site and have help with the sites hosting expenses. The Proposer gives several options for how the funds will be spent, I recommend the basic funding for three years of AD free hosting ($360) and Erics personal work to redesign the website with WordPress ($700) giving this a total of $1100.

**Comment by omisekawa** [comment]
Thanks for supporting PaywithZ.cash!
Progress and Success as of November 28, 2018
-  5 years of hosting services and domain registration secured through 10/22/2023.      
-  Website redesign with dark abstract theme, multiple pages, and easier to read formatting, optimized for mobile viewing.   
-  @PayWithZcash Twitter followers increased from 26 this spring to 147 currently.  
-  Listings of merchants and non-profits who accept Zcash increased from 29 this spring to 98 currently.   A special thanks to Dimitris A. for recently onboarding 20+ merchants in Greece.   
-  I look forward to continually updating with new merchants and non-profits, and growing with the Zcash community.

**Comment by sonyamann** [comment]
Per discussion after [Eric's last report on the general mailing list](https://lists.zfnd.org/pipermail/general/2019/000080.html), the Foundation considers this grant fulfilled and we're closing the issue. Updates on continued progress are certainly encouraged, in any venue that suits you! We look forward to the future of PayWithZ.cash 🤗
