### ISSUE TITLE
Help Blockchain Disrupt Public Education

### ISSUE THREAD

**Issue by nzeimer** [ZcashFoundation/GrantProposals-2018Q2#7]
Details of the project found here: https://hackernoon.com/cryptocreditblogpost-46409edd34e8?source=linkShare-984f0895c9a5-1524751396
NOTE: if you search my name you will see some negative articles in tabloid media. In the next month an investigative aritcle will be published in a major publication which will clear my name. Pending litigation prevents me from commenting further here at this time.

**Comment by nzeimer** [comment]
Try: http://cryptocredit.network

**Comment by tromer** [comment]
@nzeimer, I appreciate the context provided by your linked article, but can you also provide a succinct description of the concrete goals and scope of your proposal?

**Comment by tromer** [comment]
The grant review committee needs further information, as discussed above, in order to evaluate your proposal.

**Comment by tromer** [comment]
The Zcash Foundation Grant Review committee has reviewed your pre-proposal, including the above discussion, to evaluate its potential and competitiveness relative to other proposals. Every pre-proposal was evaluated by at least 4 committee members .

The committee's opinion is that *your pre-proposal is not a leading candidate for funding in this round*, and the committee therefore does not invite you to submit a full proposal.
This decision is advisory, and you can still choose to submit a full proposal by June 15th, following the detailed structure described in the [Call for Proposals](https://github.com/ZcashFoundation/GrantProposals-2018Q2). Note that if the full proposal is substantially the same as discussion so far reflects, then it's unlikely to be chosen for funding; and if it isn't, then we encourage you to post a draft (or at least answer any open questions) as early as possible, to allow for community feedback. Regardless of your choice, we thank you for participation thus far.
