### ISSUE TITLE
Create a Decentralized Identifier Method & wallet for Zcash

### ISSUE THREAD

**Issue by ChristopherA** [ZcashFoundation/GrantProposals-2018Q2#9]
Decentralized Identifiers (DIDs) are a new architecture for self-sovereign identity, originally incubated by #RebootingWebOfTrust and moving to W3C Credentials CG https://w3c-ccg.github.io 

Currently there are proposals for DID methods that work on Bitcoin, Ethereum, Sovrin, Veres One, and more. A primer: https://github.com/WebOfTrustInfo/rebooting-the-web-of-trust-fall2017/blob/master/draft-documents/did-primer.md

With basic funding we propose creating a parallel method to the Bitcoin method for Zcash anonymous web-of-trust credentials. 

With additional funding we will create open source reference code for a Zcash Identity wallet that can be used by the community to create & store Zcash DIDs and issue & hold anonymous credentials.

The team includes the author of the 10 self-sovereign identity principles & co-architect and inventor of DIDs, and a co-author of the BTCR method spec.

**Comment by eolszewski** [comment]
I've been snooping on Chris' and others' work regarding DIDs from w3c to implementations in projects like uPort. As part of a team building an open source decentralized identity system with a foundation in PGP, I can say that DIDs are quite exciting and a potentially long overdue improvement to how most are handling keys, claims, etc... Look very forward to the progress made here.

**Comment by b-g-goodell** [comment]
I think decentralized public key infrastructures are an extremely valuable route for privacy technology. Can you elaborate on evaluation plans for the project, budget, and the team (or individuals) you have in mind for the project?

**Comment by tromer** [comment]
@ChristopherA, can you describe some use cases? What will this look like from a user's perspective?

How do the anonymity/privacy features of DID relate (if at all) to the privacy features of the underlying blockchain, and in particular, how does DID on top of Zcash differe from DID on top of Bitcoin?

**Comment by ChristopherA** [comment]
I’m out of town right now (testifying on new Wyoming Blockchain laws) but plan to answer more questions next week.

**Comment by tromer** [comment]
The grant review committee needs further information, as discussed above, in order to evaluate your proposal.

**Comment by tromer** [comment]
The Zcash Foundation Grant Review committee has reviewed your pre-proposal, including the above discussion, to evaluate its potential and competitiveness relative to other proposals. Every pre-proposal was evaluated by at least 4 committee members .

The committee's opinion is that *your pre-proposal is not a leading candidate for funding in this round*, and the committee therefore does not invite you to submit a full proposal.
This decision is advisory, and you can still choose to submit a full proposal by June 15th, following the detailed structure described in the [Call for Proposals](https://github.com/ZcashFoundation/GrantProposals-2018Q2). Note that if the full proposal is substantially the same as discussion so far reflects, then it's unlikely to be chosen for funding; and if it isn't, then we encourage you to post a draft (or at least answer any open questions) as early as possible, to allow for community feedback. Regardless of your choice, we thank you for participation thus far.
